# SQL Operators Assignment – Employee Dataset

## 1. Setup: Connect to PostgreSQL

In [21]:
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv

#Load credentials from .env file
load_dotenv()

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "dbname": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD")
}

conn = psycopg2.connect(**DB_CONFIG)
conn.autocommit = True
cur = conn.cursor()
print("Connected to PostgreSQL successfully.")

Connected to PostgreSQL successfully.

## 2. Create the `employees` table

The table is created (or recreated, if it already exists) to match the 29 columns of the dataset.

In [22]:
create_table_sql = """
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    employee_id         INTEGER PRIMARY KEY,
    employee_code       VARCHAR(20),
    first_name          VARCHAR(50),
    last_name           VARCHAR(50),
    gender               VARCHAR(20),
    age                  INTEGER,
    city                 VARCHAR(50),
    department           VARCHAR(50),
    job_title            VARCHAR(100),
    employment_type      VARCHAR(30),
    join_date            DATE,
    years_experience     INTEGER,
    monthly_salary       NUMERIC(12,2),
    annual_bonus         NUMERIC(12,2),
    performance_rating   NUMERIC(3,1),
    projects_completed   INTEGER,
    leave_days_taken     INTEGER,
    overtime_hours       INTEGER,
    remote_worker        VARCHAR(5),
    employment_status    VARCHAR(20),
    education_level      VARCHAR(30),
    email                VARCHAR(100),
    phone                VARCHAR(20),
    emergency_contact    VARCHAR(20),
    manager_name         VARCHAR(100),
    certification        VARCHAR(50),
    work_shift           VARCHAR(20),
    performance_category VARCHAR(20),
    promotion_eligible   VARCHAR(5)
);
"""

cur.execute(create_table_sql)
print("Table 'employees' created.")

Table 'employees' created.

## 3. Load the dataset into the table

The dataset (`employees.csv`, exported from the original Excel file without modification)
is loaded row by row using an `INSERT` statement, with empty strings converted to `NULL`
so that `IS NULL` / `IS NOT NULL` questions work correctly.

In [23]:
df=pd.read_excel("Employee_SQL_Operators_Assignment_29_Columns.xlsx",sheet_name="Dataset")
df.to_csv("employees.csv",index=False)
print("Converted successfully!")

Converted successfully!

In [24]:

df = df.where(pd.notnull(df), None)   # convert NaN -> None (SQL NULL)

insert_sql = """
INSERT INTO employees (
    employee_id, employee_code, first_name, last_name, gender, age, city,
    department, job_title, employment_type, join_date, years_experience,
    monthly_salary, annual_bonus, performance_rating, projects_completed,
    leave_days_taken, overtime_hours, remote_worker, employment_status,
    education_level, email, phone, emergency_contact, manager_name,
    certification, work_shift, performance_category, promotion_eligible
) VALUES (
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s,
    %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s
)
"""

rows = [tuple(row) for row in df.itertuples(index=False, name=None)]
cur.executemany(insert_sql, rows)

cur.execute("SELECT COUNT(*) FROM employees;")
print("Rows loaded:", cur.fetchone()[0])

Rows loaded: 150

## 4. Helper function

A small helper to run a query and return the result as a pandas DataFrame for easy viewing.

In [25]:
def run_query(sql):
    """Run a SQL query and return results as a pandas DataFrame."""
    return pd.read_sql_query(sql, conn)

## 5. Assignment Questions (1–50)

### Q1. Arithmetic Operators\n**Display employee_id, monthly_salary, and monthly_salary + 10000 as increased_salary.**

In [26]:
query_1 = """
SELECT employee_id, monthly_salary, monthly_salary + 10000 AS increased_salary
FROM employees;
"""
run_query(query_1)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  monthly_salary  increased_salary
0              1        105000.0          115000.0
1              2        145000.0          155000.0
2              3         70000.0           80000.0
3              4        187500.0          197500.0
4              5        200000.0          210000.0
..           ...             ...               ...
145          146        210000.0          220000.0
146          147        235000.0          245000.0
147          148         45000.0           55000.0
148          149        150000.0          160000.0
149          150         37500.0           47500.0

[150 rows x 3 columns]

### Q2. Arithmetic Operators\n**Calculate reduced_salary by subtracting 5000 from monthly_salary.**

In [27]:
query_2 = """
SELECT employee_id, monthly_salary, monthly_salary - 5000 AS reduced_salary
FROM employees;
"""
run_query(query_2)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  monthly_salary  reduced_salary
0              1        105000.0        100000.0
1              2        145000.0        140000.0
2              3         70000.0         65000.0
3              4        187500.0        182500.0
4              5        200000.0        195000.0
..           ...             ...             ...
145          146        210000.0        205000.0
146          147        235000.0        230000.0
147          148         45000.0         40000.0
148          149        150000.0        145000.0
149          150         37500.0         32500.0

[150 rows x 3 columns]

### Q3. Arithmetic Operators\n**Calculate annual_salary by multiplying monthly_salary by 12.**

In [28]:
query_3 = """
SELECT employee_id, monthly_salary, monthly_salary * 12 AS annual_salary
FROM employees;
"""
run_query(query_3)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  monthly_salary  annual_salary
0              1        105000.0      1260000.0
1              2        145000.0      1740000.0
2              3         70000.0       840000.0
3              4        187500.0      2250000.0
4              5        200000.0      2400000.0
..           ...             ...            ...
145          146        210000.0      2520000.0
146          147        235000.0      2820000.0
147          148         45000.0       540000.0
148          149        150000.0      1800000.0
149          150         37500.0       450000.0

[150 rows x 3 columns]

### Q4. Arithmetic Operators\n**Calculate average_monthly_bonus by dividing annual_bonus by 12.**

In [29]:
query_4 = """
SELECT employee_id, annual_bonus, annual_bonus / 12 AS average_monthly_bonus
FROM employees;
"""
run_query(query_4)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  annual_bonus  average_monthly_bonus
0              1       15750.0            1312.500000
1              2       14500.0            1208.333333
2              3        8400.0             700.000000
3              4       15000.0            1250.000000
4              5       24000.0            2000.000000
..           ...           ...                    ...
145          146       21000.0            1750.000000
146          147       11750.0             979.166667
147          148        2250.0             187.500000
148          149       12000.0            1000.000000
149          150        1875.0             156.250000

[150 rows x 3 columns]

### Q5. Arithmetic Operators\n**Display age and age % 2 as remainder.**

In [30]:
query_5 = """
SELECT employee_id, age, age % 2 AS remainder
FROM employees;
"""
run_query(query_5)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  age  remainder
0              1   53          1
1              2   46          0
2              3   58          0
3              4   51          1
4              5   59          1
..           ...  ...        ...
145          146   28          0
146          147   40          0
147          148   35          1
148          149   39          1
149          150   52          0

[150 rows x 3 columns]

### Q6. Arithmetic Operators\n**Calculate total_compensation as (monthly_salary * 12) + annual_bonus.**

In [31]:
query_6 = """
SELECT employee_id, (monthly_salary * 12) + annual_bonus AS total_compensation
FROM employees;
"""
run_query(query_6)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

     employee_id  total_compensation
0              1           1275750.0
1              2           1754500.0
2              3            848400.0
3              4           2265000.0
4              5           2424000.0
..           ...                 ...
145          146           2541000.0
146          147           2831750.0
147          148            542250.0
148          149           1812000.0
149          150            451875.0

[150 rows x 2 columns]

### Q7. Comparison Operators\n**Find employees whose monthly_salary is greater than 100000.**

In [32]:
query_7 = """
SELECT * FROM employees
WHERE monthly_salary > 100000;
"""
run_query(query_7)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
3,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
93,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
94,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
95,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
96,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q8. Comparison Operators\n**Find employees whose age is less than 30.**

In [33]:
query_8 = """
SELECT * FROM employees
WHERE age < 30;
"""
run_query(query_8)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,10,EMP0010,Mina,Adhikari,Female,24,Biratnagar,IT,Software Engineer,Intern,...,On Leave,Diploma,mina.adhikari10@company.com,9839356575.0,9879370789.0,Amit Pandey,Python,Flexible,Good,Yes
1,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
2,15,EMP0015,Nabin,Maharjan,Other,28,Butwal,Marketing,Marketing Executive,Contract,...,On Leave,PhD,nabin.maharjan15@company.com,9847773020.0,9854365408.0,Sanjay Sharma,AWS,Flexible,Excellent,No
3,16,EMP0016,Suman,Khatri,Male,28,Bhaktapur,HR,Recruiter,Intern,...,Active,Diploma,suman.khatri16@company.com,9867011675.0,9887594913.0,Sanjay Sharma,Python,Flexible,Excellent,Yes
4,22,EMP0022,Aarav,Maharjan,Female,28,Butwal,HR,HR Manager,Full-Time,...,On Leave,PhD,aarav.maharjan22@company.com,9824263193.0,9853794068.0,Rita Thapa,Power BI,Flexible,Good,Yes
5,34,EMP0034,Binita,Poudel,Female,26,Chitwan,Sales,Sales Manager,Intern,...,On Leave,PhD,binita.poudel34@company.com,9838549945.0,NaN,Mina Rai,AWS,Flexible,Excellent,No
6,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
7,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
8,43,EMP0043,Amit,Sharma,Female,23,Chitwan,Finance,Accountant,Intern,...,Active,Master,amit.sharma43@company.com,9817143479.0,9882701840.0,Mina Rai,AWS,Day,Excellent,No
9,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
10,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
11,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
12,60,EMP0060,Roshani,Shrestha,Other,27,Butwal,IT,Data Engineer,Part-Time,...,Active,Diploma,roshani.shrestha60@company.com,9864888845.0,9859795676.0,Prakash Karki,PMP,Evening,Excellent,No
13,75,EMP0075,Kiran,Tamang,Female,26,Kathmandu,Marketing,Content Specialist,Part-Time,...,On Leave,Master,kiran.tamang75@company.com,9810752947.0,9894539529.0,Prakash Karki,Python,Evening,Excellent,No
14,83,EMP0083,Pooja,KC,Female,24,Pokhara,Sales,Sales Manager,Contract,...,On Leave,PhD,pooja.kc83@company.com,9854881134.0,9837460878.0,Amit Pandey,AWS,Evening,Excellent,Yes
15,86,EMP0086,Pratigya,Thapa,Female,21,Chitwan,Finance,Financial Analyst,Part-Time,...,Active,Diploma,pratigya.thapa86@company.com,9878479872.0,9838354028.0,Sanjay Sharma,AWS,Flexible,Average,Yes
16,87,EMP0087,Kiran,Tamang,Male,29,Bhaktapur,Analytics,Data Analyst,Contract,...,Inactive,Bachelor,kiran.tamang87@company.com,9875621662.0,9881447513.0,Rita Thapa,Power BI,Evening,Good,Yes
17,91,EMP0091,Kiran,Poudel,Other,29,Lalitpur,Sales,Business Development Officer,Full-Time,...,On Leave,Master,kiran.poudel91@company.com,9820708628.0,9864900957.0,Prakash Karki,None,Day,Average,Yes
18,123,EMP0123,Suman,Karki,Other,21,Biratnagar,Operations,Operations Officer,Part-Time,...,On Leave,Bachelor,suman.karki123@company.com,9864398068.0,9821959510.0,Rita Thapa,AWS,Evening,Excellent,Yes
19,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
20,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
21,129,EMP0129,Sita,Pandey,Female,22,Butwal,Operations,Operations Officer,Intern,...,Inactive,Master,sita.pandey129@company.com,9866344237.0,9874422393.0,Rita Thapa,AWS,Evening,Good,No
22,136,EMP0136,Prakash,Maharjan,Male,22,Pokhara,Operations,Operations Manager,Full-Time,...,On Leave,Master,prakash.maharjan136@company.com,9846381299.0,NaN,Sanjay Sharma,Python,Day,Good,Yes
23,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
24,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
25,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
26,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No

### Q9. Comparison Operators\n**Find employees with performance_rating greater than or equal to 4.5.**

In [34]:
query_9 = """
SELECT * FROM employees
WHERE performance_rating >= 4.5;
"""
run_query(query_9)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
1,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
2,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
3,12,EMP0012,Mina,Tamang,Other,47,Biratnagar,Marketing,Marketing Executive,Contract,...,Inactive,PhD,mina.tamang12@company.com,9893320274.0,9847644351.0,Sanjay Sharma,PMP,Flexible,Average,Yes
4,20,EMP0020,Suman,Gurung,Other,58,Bhaktapur,IT,Data Engineer,Contract,...,On Leave,Bachelor,suman.gurung20@company.com,9824082320.0,9821480544.0,Amit Pandey,Python,Flexible,Average,Yes
5,21,EMP0021,Sneha,Rai,Male,39,Butwal,HR,HR Manager,Part-Time,...,Inactive,Bachelor,sneha.rai21@company.com,9896943854.0,9874426133.0,Amit Pandey,Power BI,Day,Good,Yes
6,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
7,43,EMP0043,Amit,Sharma,Female,23,Chitwan,Finance,Accountant,Intern,...,Active,Master,amit.sharma43@company.com,9817143479.0,9882701840.0,Mina Rai,AWS,Day,Excellent,No
8,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
9,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
10,71,EMP0071,Sneha,Karki,Other,50,Kathmandu,Analytics,Data Scientist,Part-Time,...,Active,PhD,sneha.karki71@company.com,9826061271.0,9847600699.0,Sanjay Sharma,SQL,Flexible,Good,Yes
11,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
12,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
13,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
14,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
15,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
16,82,EMP0082,Rahul,Thapa,Female,45,Kathmandu,Finance,Finance Officer,Intern,...,Inactive,Bachelor,rahul.thapa82@company.com,9814408661.0,9896296613.0,Mina Rai,PMP,Day,Excellent,Yes
17,90,EMP0090,Binita,Adhikari,Other,50,Lalitpur,HR,HR Officer,Part-Time,...,On Leave,Master,binita.adhikari90@company.com,9844174538.0,9848430671.0,Prakash Karki,Power BI,Day,Good,No
18,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
19,93,EMP0093,Rahul,Khatri,Female,52,Kathmandu,HR,HR Manager,Intern,...,Inactive,Master,rahul.khatri93@company.com,9835004522.0,9876875826.0,Prakash Karki,PMP,Evening,Good,Yes
20,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
21,102,EMP0102,Ramesh,Sharma,Male,57,Lalitpur,Operations,Project Coordinator,Full-Time,...,On Leave,PhD,ramesh.sharma102@company.com,9828945559.0,NaN,Prakash Karki,AWS,Flexible,Average,Yes
22,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
23,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No
24,117,EMP0117,Anish,Poudel,Male,53,Lalitpur,Finance,Accountant,Part-Time,...,Inactive,Master,anish.poudel117@company.com,9861663450.0,9853848371.0,Prakash Karki,None,Day,Good,Yes
25,121,EMP0121,Sanjay,Adhikari,Male,47,Pokhara,Finance,Finance Officer,Part-Time,...,On Leave,Diploma,sanjay.adhikari121@company.com,9864490608.0,9825305380.0,Mina Rai,Python,Evening,Average,Yes
26,127,EMP0127,Prakash,Rai,Female,50,Bhaktapur,Marketing,Brand Manager,Intern,...,Inactive,Master,prakash.rai127@company.com,9871549258.0,9848005441.0,Rita Thapa,None,Day,Good,No
27,135,EMP0135,Bikash,Rai,Other,57,Butwal,Operations,Operations Officer,Contract,...,Inactive,PhD,bikash.rai135@company.com,9855378650.0,9845380680.0,Prakash Karki,PMP,Day,Excellent,Yes
28,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
29,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
30,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
31,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No

### Q10. Comparison Operators\n**Find employees whose years_experience is less than or equal to 5.**

In [35]:
query_10 = """
SELECT * FROM employees
WHERE years_experience <= 5;
"""
run_query(query_10)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
1,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
76,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
77,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
78,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
79,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q11. Comparison Operators\n**Find employees whose department is equal to IT.**

In [36]:
query_11 = """
SELECT * FROM employees
WHERE department = 'IT';
"""
run_query(query_11)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,10,EMP0010,Mina,Adhikari,Female,24,Biratnagar,IT,Software Engineer,Intern,...,On Leave,Diploma,mina.adhikari10@company.com,9839356575.0,9879370789.0,Amit Pandey,Python,Flexible,Good,Yes
4,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
5,14,EMP0014,Rita,Poudel,Male,37,Chitwan,IT,QA Engineer,Full-Time,...,On Leave,PhD,rita.poudel14@company.com,9887373976.0,9857017385.0,Amit Pandey,AWS,Flexible,Excellent,No
6,20,EMP0020,Suman,Gurung,Other,58,Bhaktapur,IT,Data Engineer,Contract,...,On Leave,Bachelor,suman.gurung20@company.com,9824082320.0,9821480544.0,Amit Pandey,Python,Flexible,Average,Yes
7,26,EMP0026,Nabin,Karki,Other,52,Lalitpur,IT,Software Engineer,Contract,...,Inactive,Diploma,nabin.karki26@company.com,9845843496.0,9885017167.0,Sanjay Sharma,None,Evening,Good,No
8,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
9,31,EMP0031,Sabina,Gurung,Other,34,Bhaktapur,IT,QA Engineer,Part-Time,...,Active,Master,sabina.gurung31@company.com,9885012599.0,9853722847.0,Rita Thapa,AWS,Flexible,Excellent,Yes
10,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
11,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
12,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
13,60,EMP0060,Roshani,Shrestha,Other,27,Butwal,IT,Data Engineer,Part-Time,...,Active,Diploma,roshani.shrestha60@company.com,9864888845.0,9859795676.0,Prakash Karki,PMP,Evening,Excellent,No
14,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
15,94,EMP0094,Rahul,Pandey,Other,49,Pokhara,IT,Software Engineer,Contract,...,Active,PhD,rahul.pandey94@company.com,9873692578.0,9868982824.0,Mina Rai,Power BI,Day,Good,No
16,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
17,106,EMP0106,Deepak,Poudel,Female,48,Biratnagar,IT,Data Engineer,Contract,...,On Leave,Diploma,deepak.poudel106@company.com,9864110841.0,9824857172.0,Prakash Karki,PMP,Flexible,Excellent,No
18,109,EMP0109,Sujan,Tamang,Male,44,Chitwan,IT,Data Engineer,Part-Time,...,Active,Diploma,sujan.tamang109@company.com,9882571368.0,9883310657.0,Sanjay Sharma,None,Day,Good,No
19,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
20,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
21,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes

### Q12. Comparison Operators\n**Find employees whose employment_status is not equal to Active.**

In [37]:
query_12 = """
SELECT * FROM employees
WHERE employment_status <> 'Active';
"""
run_query(query_12)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
1,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
4,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,136,EMP0136,Prakash,Maharjan,Male,22,Pokhara,Operations,Operations Manager,Full-Time,...,On Leave,Master,prakash.maharjan136@company.com,9846381299.0,NaN,Sanjay Sharma,Python,Day,Good,Yes
93,137,EMP0137,Amit,Karki,Female,42,Lalitpur,Sales,Sales Executive,Contract,...,On Leave,Diploma,amit.karki137@company.com,9877977817.0,9825138757.0,Prakash Karki,SQL,Evening,Excellent,Yes
94,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
95,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
96,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes

### Q13. Logical Operators\n**Find employees from Kathmandu AND monthly_salary greater than 100000.**

In [38]:
query_13 = """
SELECT * FROM employees
WHERE city = 'Kathmandu' AND monthly_salary > 100000;
"""
run_query(query_13)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
2,33,EMP0033,Aarav,Rai,Female,35,Kathmandu,Sales,Sales Executive,Contract,...,Inactive,PhD,aarav.rai33@company.com,9878214548.0,9815405350.0,Rita Thapa,Power BI,Evening,Excellent,Yes
3,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
4,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
5,48,EMP0048,Ramesh,Rai,Other,49,Kathmandu,Analytics,Data Analyst,Part-Time,...,Inactive,PhD,ramesh.rai48@company.com,9832568994.0,9823644673.0,Prakash Karki,PMP,Flexible,Good,Yes
6,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
7,63,EMP0063,Suman,Shrestha,Other,55,Kathmandu,Sales,Sales Manager,Contract,...,Inactive,Diploma,suman.shrestha63@company.com,9836063000.0,9884127728.0,Rita Thapa,AWS,Evening,Excellent,Yes
8,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
9,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
10,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
11,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
12,82,EMP0082,Rahul,Thapa,Female,45,Kathmandu,Finance,Finance Officer,Intern,...,Inactive,Bachelor,rahul.thapa82@company.com,9814408661.0,9896296613.0,Mina Rai,PMP,Day,Excellent,Yes
13,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
14,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
15,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
16,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
17,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes

### Q14. Logical Operators\n**Find employees from Kathmandu OR Pokhara.**

In [39]:
query_14 = """
SELECT * FROM employees
WHERE city = 'Kathmandu' OR city = 'Pokhara';
"""
run_query(query_14)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
2,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
3,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
4,28,EMP0028,Amit,Sharma,Female,31,Pokhara,HR,HR Manager,Part-Time,...,On Leave,PhD,amit.sharma28@company.com,9813798947.0,9846356183.0,Sanjay Sharma,Power BI,Evening,Good,No
5,30,EMP0030,Anish,Basnet,Male,53,Pokhara,Analytics,Data Analyst,Part-Time,...,On Leave,Diploma,anish.basnet30@company.com,9852672583.0,9898658609.0,Mina Rai,AWS,Flexible,Excellent,Yes
6,32,EMP0032,Pratigya,Karki,Male,57,Pokhara,Analytics,Data Analyst,Full-Time,...,Active,Master,pratigya.karki32@company.com,9882520415.0,9857868867.0,Prakash Karki,Python,Evening,Average,No
7,33,EMP0033,Aarav,Rai,Female,35,Kathmandu,Sales,Sales Executive,Contract,...,Inactive,PhD,aarav.rai33@company.com,9878214548.0,9815405350.0,Rita Thapa,Power BI,Evening,Excellent,Yes
8,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
9,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
10,44,EMP0044,Suman,Shrestha,Male,49,Kathmandu,Marketing,Marketing Executive,Contract,...,Active,Master,suman.shrestha44@company.com,9896723552.0,9897990221.0,Prakash Karki,Python,Flexible,Average,Yes
11,48,EMP0048,Ramesh,Rai,Other,49,Kathmandu,Analytics,Data Analyst,Part-Time,...,Inactive,PhD,ramesh.rai48@company.com,9832568994.0,9823644673.0,Prakash Karki,PMP,Flexible,Good,Yes
12,52,EMP0052,Sanjay,Lama,Male,46,Kathmandu,HR,Recruiter,Contract,...,Inactive,Bachelor,sanjay.lama52@company.com,9825693263.0,9839171865.0,Sanjay Sharma,None,Evening,Excellent,No
13,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
14,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
15,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
16,63,EMP0063,Suman,Shrestha,Other,55,Kathmandu,Sales,Sales Manager,Contract,...,Inactive,Diploma,suman.shrestha63@company.com,9836063000.0,9884127728.0,Rita Thapa,AWS,Evening,Excellent,Yes
17,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
18,71,EMP0071,Sneha,Karki,Other,50,Kathmandu,Analytics,Data Scientist,Part-Time,...,Active,PhD,sneha.karki71@company.com,9826061271.0,9847600699.0,Sanjay Sharma,SQL,Flexible,Good,Yes
19,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
20,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
21,75,EMP0075,Kiran,Tamang,Female,26,Kathmandu,Marketing,Content Specialist,Part-Time,...,On Leave,Master,kiran.tamang75@company.com,9810752947.0,9894539529.0,Prakash Karki,Python,Evening,Excellent,No
22,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
23,82,EMP0082,Rahul,Thapa,Female,45,Kathmandu,Finance,Finance Officer,Intern,...,Inactive,Bachelor,rahul.thapa82@company.com,9814408661.0,9896296613.0,Mina Rai,PMP,Day,Excellent,Yes
24,83,EMP0083,Pooja,KC,Female,24,Pokhara,Sales,Sales Manager,Contract,...,On Leave,PhD,pooja.kc83@company.com,9854881134.0,9837460878.0,Amit Pandey,AWS,Evening,Excellent,Yes
25,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
26,93,EMP0093,Rahul,Khatri,Female,52,Kathmandu,HR,HR Manager,Intern,...,Inactive,Master,rahul.khatri93@company.com,9835004522.0,9876875826.0,Prakash Karki,PMP,Evening,Good,Yes
27,94,EMP0094,Rahul,Pandey,Other,49,Pokhara,IT,Software Engineer,Contract,...,Active,PhD,rahul.pandey94@company.com,9873692578.0,9868982824.0,Mina Rai,Power BI,Day,Good,No
28,103,EMP0103,Ramesh,Tamang,Other,44,Pokhara,Operations,Project Coordinator,Full-Time,...,Inactive,PhD,ramesh.tamang103@company.com,9820182234.0,9879899607.0,Mina Rai,Power BI,Evening,Excellent,Yes
29,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
30,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
31,113,EMP0113,Anish,Rai,Female,50,Pokhara,Marketing,Brand Manager,Intern,...,On Leave,PhD,anish.rai113@company.com,9875495240.0,9874249204.0,Amit Pandey,SQL,Day,Good,Yes
32,114,EMP0114,Aarya,Lama,Other,47,Kathmandu,Analytics,Data Scientist,Part-Time,...,Inactive,Bachelor,None,9838411370.0,9836421875.0,Prakash Karki,AWS,Flexible,Good,No
33,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
34,121,EMP0121,Sanjay,Adhikari,Male,47,Pokhara,Finance,Finance Officer,Part-Time,...,On Leave,Diploma,sanjay.adhikari121@company.com,9864490608.0,9825305380.0,Mina Rai,Python,Evening,Average,Yes
35,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
36,136,EMP0136,Prakash,Maharjan,Male,22,Pokhara,Operations,Operations Manager,Full-Time,...,On Leave,Master,prakash.maharjan136@company.com,9846381299.0,NaN,Sanjay Sharma,Python,Day,Good,Yes
37,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
38,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No
39,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
40,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
41,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q15. Logical Operators\n**Find employees from IT OR Analytics with performance_rating greater than 4.**

In [40]:
query_15 = """
SELECT * FROM employees
WHERE (department = 'IT' OR department = 'Analytics')
  AND performance_rating > 4;
"""
run_query(query_15)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
2,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
3,20,EMP0020,Suman,Gurung,Other,58,Bhaktapur,IT,Data Engineer,Contract,...,On Leave,Bachelor,suman.gurung20@company.com,9824082320.0,9821480544.0,Amit Pandey,Python,Flexible,Average,Yes
4,26,EMP0026,Nabin,Karki,Other,52,Lalitpur,IT,Software Engineer,Contract,...,Inactive,Diploma,nabin.karki26@company.com,9845843496.0,9885017167.0,Sanjay Sharma,None,Evening,Good,No
5,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
6,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
7,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
8,51,EMP0051,Nabin,Poudel,Other,60,Lalitpur,Analytics,Data Analyst,Intern,...,On Leave,Bachelor,nabin.poudel51@company.com,9867614636.0,NaN,Amit Pandey,Power BI,Day,Excellent,Yes
9,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
10,69,EMP0069,Binita,Basnet,Male,59,Butwal,Analytics,Data Analyst,Intern,...,On Leave,PhD,binita.basnet69@company.com,NaN,9863222909.0,Rita Thapa,Power BI,Flexible,Excellent,No
11,71,EMP0071,Sneha,Karki,Other,50,Kathmandu,Analytics,Data Scientist,Part-Time,...,Active,PhD,sneha.karki71@company.com,9826061271.0,9847600699.0,Sanjay Sharma,SQL,Flexible,Good,Yes
12,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
13,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
14,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
15,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
16,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes

### Q16. Logical Operators\n**Find employees who are NOT remote workers.**

In [41]:
query_16 = """
SELECT * FROM employees
WHERE NOT remote_worker = 'Yes';
"""
run_query(query_16)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
4,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
71,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
72,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
73,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
74,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q17. Logical Operators\n**Find employees with age below 40 AND years_experience above 5 AND employment_status = Active.**

In [42]:
query_17 = """
SELECT * FROM employees
WHERE age < 40
  AND years_experience > 5
  AND employment_status = 'Active';
"""
run_query(query_17)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,16,EMP0016,Suman,Khatri,Male,28,Bhaktapur,HR,Recruiter,Intern,...,Active,Diploma,suman.khatri16@company.com,9867011675.0,9887594913.0,Sanjay Sharma,Python,Flexible,Excellent,Yes
1,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
2,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
3,60,EMP0060,Roshani,Shrestha,Other,27,Butwal,IT,Data Engineer,Part-Time,...,Active,Diploma,roshani.shrestha60@company.com,9864888845.0,9859795676.0,Prakash Karki,PMP,Evening,Excellent,No
4,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
5,77,EMP0077,Roshani,Lama,Other,31,Butwal,Sales,Sales Executive,Intern,...,Active,PhD,roshani.lama77@company.com,9818242695.0,9827301329.0,Mina Rai,Power BI,Flexible,Excellent,Yes
6,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
7,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
8,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
9,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No
10,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
11,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
12,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
13,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q18. Logical Operators\n**Find Full-Time employees with salary above 80000 OR performance_rating above 4.5.**

In [43]:
query_18 = """
SELECT * FROM employees
WHERE employment_type = 'Full-Time'
  AND (monthly_salary > 80000 OR performance_rating > 4.5);
"""
run_query(query_18)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
1,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
2,17,EMP0017,Suman,Khatri,Female,55,Biratnagar,HR,HR Manager,Full-Time,...,Active,Bachelor,suman.khatri17@company.com,9845408799.0,NaN,Mina Rai,AWS,Flexible,Average,No
3,22,EMP0022,Aarav,Maharjan,Female,28,Butwal,HR,HR Manager,Full-Time,...,On Leave,PhD,aarav.maharjan22@company.com,9824263193.0,9853794068.0,Rita Thapa,Power BI,Flexible,Good,Yes
4,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
5,32,EMP0032,Pratigya,Karki,Male,57,Pokhara,Analytics,Data Analyst,Full-Time,...,Active,Master,pratigya.karki32@company.com,9882520415.0,9857868867.0,Prakash Karki,Python,Evening,Average,No
6,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
7,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
8,59,EMP0059,Ramesh,Rai,Other,37,Chitwan,Finance,Finance Officer,Full-Time,...,On Leave,Master,ramesh.rai59@company.com,9882437717.0,9871221053.0,Amit Pandey,SQL,Day,Good,Yes
9,64,EMP0064,Bikash,Tamang,Male,51,Bhaktapur,Analytics,Data Scientist,Full-Time,...,On Leave,Master,bikash.tamang64@company.com,9856325053.0,9840377727.0,Amit Pandey,None,Evening,Good,No
10,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
11,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
12,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
13,91,EMP0091,Kiran,Poudel,Other,29,Lalitpur,Sales,Business Development Officer,Full-Time,...,On Leave,Master,kiran.poudel91@company.com,9820708628.0,9864900957.0,Prakash Karki,None,Day,Average,Yes
14,100,EMP0100,Roshani,Maharjan,Other,42,Biratnagar,Sales,Sales Executive,Full-Time,...,Active,Master,roshani.maharjan100@company.com,9899824730.0,9843196434.0,Prakash Karki,PMP,Evening,Good,Yes
15,102,EMP0102,Ramesh,Sharma,Male,57,Lalitpur,Operations,Project Coordinator,Full-Time,...,On Leave,PhD,ramesh.sharma102@company.com,9828945559.0,NaN,Prakash Karki,AWS,Flexible,Average,Yes
16,103,EMP0103,Ramesh,Tamang,Other,44,Pokhara,Operations,Project Coordinator,Full-Time,...,Inactive,PhD,ramesh.tamang103@company.com,9820182234.0,9879899607.0,Mina Rai,Power BI,Evening,Excellent,Yes
17,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
18,107,EMP0107,Roshani,Rai,Female,45,Biratnagar,HR,Recruiter,Full-Time,...,Active,PhD,roshani.rai107@company.com,9846019197.0,9883539296.0,Amit Pandey,AWS,Flexible,Good,No
19,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
20,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
21,132,EMP0132,Amit,KC,Other,31,Butwal,Finance,Finance Officer,Full-Time,...,On Leave,Master,amit.kc132@company.com,9825304867.0,9883974314.0,Mina Rai,AWS,Evening,Average,No
22,134,EMP0134,Sanjay,Khatri,Other,54,Butwal,Finance,Finance Officer,Full-Time,...,On Leave,Master,sanjay.khatri134@company.com,9899711916.0,9887173967.0,Amit Pandey,Power BI,Flexible,Excellent,No
23,136,EMP0136,Prakash,Maharjan,Male,22,Pokhara,Operations,Operations Manager,Full-Time,...,On Leave,Master,prakash.maharjan136@company.com,9846381299.0,NaN,Sanjay Sharma,Python,Day,Good,Yes
24,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
25,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
26,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
27,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q19. LIKE Operator\n**Find employees whose first_name starts with A.**

In [44]:
query_19 = """
SELECT * FROM employees
WHERE first_name LIKE 'A%';
"""
run_query(query_19)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
1,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
2,22,EMP0022,Aarav,Maharjan,Female,28,Butwal,HR,HR Manager,Full-Time,...,On Leave,PhD,aarav.maharjan22@company.com,9824263193.0,9853794068.0,Rita Thapa,Power BI,Flexible,Good,Yes
3,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
4,28,EMP0028,Amit,Sharma,Female,31,Pokhara,HR,HR Manager,Part-Time,...,On Leave,PhD,amit.sharma28@company.com,9813798947.0,9846356183.0,Sanjay Sharma,Power BI,Evening,Good,No
5,30,EMP0030,Anish,Basnet,Male,53,Pokhara,Analytics,Data Analyst,Part-Time,...,On Leave,Diploma,anish.basnet30@company.com,9852672583.0,9898658609.0,Mina Rai,AWS,Flexible,Excellent,Yes
6,33,EMP0033,Aarav,Rai,Female,35,Kathmandu,Sales,Sales Executive,Contract,...,Inactive,PhD,aarav.rai33@company.com,9878214548.0,9815405350.0,Rita Thapa,Power BI,Evening,Excellent,Yes
7,40,EMP0040,Aarav,Pandey,Male,34,Chitwan,Sales,Business Development Officer,Part-Time,...,Inactive,Bachelor,aarav.pandey40@company.com,9867943072.0,9887892505.0,Prakash Karki,SQL,Flexible,Good,Yes
8,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
9,43,EMP0043,Amit,Sharma,Female,23,Chitwan,Finance,Accountant,Intern,...,Active,Master,amit.sharma43@company.com,9817143479.0,9882701840.0,Mina Rai,AWS,Day,Excellent,No
10,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
11,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
12,57,EMP0057,Anita,Poudel,Other,59,Bhaktapur,Finance,Finance Officer,Intern,...,Inactive,Bachelor,None,9864493103.0,9896832664.0,Prakash Karki,Power BI,Evening,Good,No
13,66,EMP0066,Aarav,Khatri,Male,41,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Diploma,aarav.khatri66@company.com,9892618075.0,9839377581.0,Amit Pandey,SQL,Flexible,Good,Yes
14,70,EMP0070,Anish,Poudel,Female,33,Lalitpur,Sales,Business Development Officer,Contract,...,Inactive,Bachelor,anish.poudel70@company.com,9864526378.0,9872613862.0,Amit Pandey,Power BI,Flexible,Excellent,No
15,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
16,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
17,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
18,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
19,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
20,81,EMP0081,Aarav,Karki,Female,59,Bhaktapur,Operations,Operations Manager,Full-Time,...,Active,Master,aarav.karki81@company.com,9850081864.0,9826393507.0,Sanjay Sharma,AWS,Day,Average,Yes
21,98,EMP0098,Amit,Karki,Other,39,Lalitpur,Finance,Finance Officer,Contract,...,Active,PhD,amit.karki98@company.com,9816172851.0,9813752892.0,Prakash Karki,Power BI,Flexible,Excellent,Yes
22,108,EMP0108,Anish,Poudel,Other,52,Butwal,Sales,Business Development Officer,Contract,...,On Leave,Diploma,anish.poudel108@company.com,9875760905.0,9889712241.0,Sanjay Sharma,Power BI,Evening,Good,No
23,111,EMP0111,Aarya,Tamang,Female,54,Butwal,Finance,Accountant,Part-Time,...,Inactive,Master,aarya.tamang111@company.com,9888759129.0,9821730882.0,Mina Rai,SQL,Flexible,Average,Yes
24,113,EMP0113,Anish,Rai,Female,50,Pokhara,Marketing,Brand Manager,Intern,...,On Leave,PhD,anish.rai113@company.com,9875495240.0,9874249204.0,Amit Pandey,SQL,Day,Good,Yes
25,114,EMP0114,Aarya,Lama,Other,47,Kathmandu,Analytics,Data Scientist,Part-Time,...,Inactive,Bachelor,None,9838411370.0,9836421875.0,Prakash Karki,AWS,Flexible,Good,No
26,117,EMP0117,Anish,Poudel,Male,53,Lalitpur,Finance,Accountant,Part-Time,...,Inactive,Master,anish.poudel117@company.com,9861663450.0,9853848371.0,Prakash Karki,None,Day,Good,Yes
27,120,EMP0120,Amit,Poudel,Female,31,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,amit.poudel120@company.com,9884589166.0,9869481985.0,Rita Thapa,Python,Evening,Average,Yes
28,122,EMP0122,Aarya,Basnet,Male,51,Lalitpur,Marketing,Content Specialist,Contract,...,Active,Diploma,aarya.basnet122@company.com,9872692830.0,9840366343.0,Mina Rai,Python,Evening,Excellent,No
29,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
30,132,EMP0132,Amit,KC,Other,31,Butwal,Finance,Finance Officer,Full-Time,...,On Leave,Master,amit.kc132@company.com,9825304867.0,9883974314.0,Mina Rai,AWS,Evening,Average,No
31,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
32,137,EMP0137,Amit,Karki,Female,42,Lalitpur,Sales,Sales Executive,Contract,...,On Leave,Diploma,amit.karki137@company.com,9877977817.0,9825138757.0,Prakash Karki,SQL,Evening,Excellent,Yes
33,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
34,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
35,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
36,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q20. LIKE Operator\n**Find employees whose first_name ends with a.**

In [45]:
query_20 = """
SELECT * FROM employees
WHERE first_name LIKE '%a';
"""
run_query(query_20)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
1,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
2,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
3,10,EMP0010,Mina,Adhikari,Female,24,Biratnagar,IT,Software Engineer,Intern,...,On Leave,Diploma,mina.adhikari10@company.com,9839356575.0,9879370789.0,Amit Pandey,Python,Flexible,Good,Yes
4,11,EMP0011,Nisha,Thapa,Male,43,Bhaktapur,Marketing,Marketing Executive,Contract,...,Active,Master,nisha.thapa11@company.com,9833751475.0,9853726695.0,Mina Rai,PMP,Day,Excellent,Yes
5,12,EMP0012,Mina,Tamang,Other,47,Biratnagar,Marketing,Marketing Executive,Contract,...,Inactive,PhD,mina.tamang12@company.com,9893320274.0,9847644351.0,Sanjay Sharma,PMP,Flexible,Average,Yes
6,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
7,14,EMP0014,Rita,Poudel,Male,37,Chitwan,IT,QA Engineer,Full-Time,...,On Leave,PhD,rita.poudel14@company.com,9887373976.0,9857017385.0,Amit Pandey,AWS,Flexible,Excellent,No
8,18,EMP0018,Mina,Adhikari,Male,41,Butwal,Finance,Financial Analyst,Contract,...,On Leave,Master,mina.adhikari18@company.com,9830246318.0,9863562849.0,Amit Pandey,None,Evening,Good,No
9,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
10,21,EMP0021,Sneha,Rai,Male,39,Butwal,HR,HR Manager,Part-Time,...,Inactive,Bachelor,sneha.rai21@company.com,9896943854.0,9874426133.0,Amit Pandey,Power BI,Day,Good,Yes
11,25,EMP0025,Pratigya,Poudel,Other,49,Bhaktapur,Finance,Accountant,Full-Time,...,Inactive,PhD,pratigya.poudel25@company.com,9849388796.0,9887093109.0,Prakash Karki,Power BI,Flexible,Good,No
12,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
13,31,EMP0031,Sabina,Gurung,Other,34,Bhaktapur,IT,QA Engineer,Part-Time,...,Active,Master,sabina.gurung31@company.com,9885012599.0,9853722847.0,Rita Thapa,AWS,Flexible,Excellent,Yes
14,32,EMP0032,Pratigya,Karki,Male,57,Pokhara,Analytics,Data Analyst,Full-Time,...,Active,Master,pratigya.karki32@company.com,9882520415.0,9857868867.0,Prakash Karki,Python,Evening,Average,No
15,34,EMP0034,Binita,Poudel,Female,26,Chitwan,Sales,Sales Manager,Intern,...,On Leave,PhD,binita.poudel34@company.com,9838549945.0,NaN,Mina Rai,AWS,Flexible,Excellent,No
16,42,EMP0042,Pratigya,Sharma,Female,56,Lalitpur,Operations,Operations Officer,Part-Time,...,Inactive,Bachelor,pratigya.sharma42@company.com,9897299598.0,9897403192.0,Rita Thapa,Power BI,Evening,Excellent,Yes
17,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
18,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
19,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
20,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
21,57,EMP0057,Anita,Poudel,Other,59,Bhaktapur,Finance,Finance Officer,Intern,...,Inactive,Bachelor,None,9864493103.0,9896832664.0,Prakash Karki,Power BI,Evening,Good,No
22,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
23,69,EMP0069,Binita,Basnet,Male,59,Butwal,Analytics,Data Analyst,Intern,...,On Leave,PhD,binita.basnet69@company.com,NaN,9863222909.0,Rita Thapa,Power BI,Flexible,Excellent,No
24,71,EMP0071,Sneha,Karki,Other,50,Kathmandu,Analytics,Data Scientist,Part-Time,...,Active,PhD,sneha.karki71@company.com,9826061271.0,9847600699.0,Sanjay Sharma,SQL,Flexible,Good,Yes
25,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
26,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
27,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
28,79,EMP0079,Runa,Poudel,Other,54,Biratnagar,Marketing,Marketing Executive,Intern,...,On Leave,Master,runa.poudel79@company.com,9825926241.0,9871094430.0,Prakash Karki,None,Flexible,Good,No
29,83,EMP0083,Pooja,KC,Female,24,Pokhara,Sales,Sales Manager,Contract,...,On Leave,PhD,pooja.kc83@company.com,9854881134.0,9837460878.0,Amit Pandey,AWS,Evening,Excellent,Yes
30,85,EMP0085,Pooja,Khatri,Female,59,Biratnagar,Sales,Sales Executive,Part-Time,...,Active,PhD,pooja.khatri85@company.com,9820233067.0,NaN,Mina Rai,SQL,Day,Excellent,Yes
31,86,EMP0086,Pratigya,Thapa,Female,21,Chitwan,Finance,Financial Analyst,Part-Time,...,Active,Diploma,pratigya.thapa86@company.com,9878479872.0,9838354028.0,Sanjay Sharma,AWS,Flexible,Average,Yes
32,88,EMP0088,Pratigya,KC,Other,54,Bhaktapur,Finance,Accountant,Contract,...,Inactive,Diploma,pratigya.kc88@company.com,9895239113.0,9831021022.0,Sanjay Sharma,PMP,Evening,Good,Yes
33,89,EMP0089,Pratigya,Maharjan,Male,50,Bhaktapur,Finance,Financial Analyst,Intern,...,Active,PhD,pratigya.maharjan89@company.com,9848204430.0,9887110232.0,Sanjay Sharma,Power BI,Evening,Good,Yes
34,90,EMP0090,Binita,Adhikari,Other,50,Lalitpur,HR,HR Officer,Part-Time,...,On Leave,Master,binita.adhikari90@company.com,9844174538.0,9848430671.0,Prakash Karki,Power BI,Day,Good,No
35,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
36,95,EMP0095,Mina,Karki,Female,59,Biratnagar,Marketing,Content Specialist,Intern,...,Inactive,Diploma,None,9839052337.0,9832589858.0,Rita Thapa,SQL,Flexible,Excellent,Yes
37,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
38,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
39,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
40,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
41,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
42,111,EMP0111,Aarya,Tamang,Female,54,Butwal,Finance,Accountant,Part-Time,...,Inactive,Master,aarya.tamang111@company.com,9888759129.0,9821730882.0,Mina Rai,SQL,Flexible,Average,Yes
43,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No
44,114,EMP0114,Aarya,Lama,Other,47,Kathmandu,Analytics,Data Scientist,Part-Time,...,Inactive,Bachelor,None,9838411370.0,9836421875.0,Prakash Karki,AWS,Flexible,Good,No
45,119,EMP0119,Runa,Pandey,Other,44,Lalitpur,HR,HR Officer,Contract,...,Inactive,PhD,runa.pandey119@company.com,9846081313.0,NaN,Mina Rai,AWS,Flexible,Average,Yes
46,122,EMP0122,Aarya,Basnet,Male,51,Lalitpur,Marketing,Content Specialist,Contract,...,Active,Diploma,aarya.basnet122@company.com,9872692830.0,9840366343.0,Mina Rai,Python,Evening,Excellent,No
47,124,EMP0124,Mina,Tamang,Other,51,Biratnagar,Marketing,Content Specialist,Part-Time,...,Inactive,Master,mina.tamang124@company.com,9885442780.0,9821786936.0,Prakash Karki,PMP,Day,Average,Yes
48,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
49,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
50,129,EMP0129,Sita,Pandey,Female,22,Butwal,Operations,Operations Officer,Intern,...,Inactive,Master,sita.pandey129@company.com,9866344237.0,9874422393.0,Rita Thapa,AWS,Evening,Good,No
51,131,EMP0131,Rita,Pandey,Other,48,Butwal,HR,HR Officer,Contract,...,Active,Master,rita.pandey131@company.com,9867615075.0,9846545625.0,Sanjay Sharma,PMP,Flexible,Good,No
52,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
53,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
54,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
55,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
56,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
57,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
58,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q21. LIKE Operator\n**Find employees whose first_name contains the letter i.**

In [46]:
query_21 = """
SELECT * FROM employees
WHERE first_name LIKE '%i%';
"""
run_query(query_21)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
1,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
2,10,EMP0010,Mina,Adhikari,Female,24,Biratnagar,IT,Software Engineer,Intern,...,On Leave,Diploma,mina.adhikari10@company.com,9839356575.0,9879370789.0,Amit Pandey,Python,Flexible,Good,Yes
3,11,EMP0011,Nisha,Thapa,Male,43,Bhaktapur,Marketing,Marketing Executive,Contract,...,Active,Master,nisha.thapa11@company.com,9833751475.0,9853726695.0,Mina Rai,PMP,Day,Excellent,Yes
4,12,EMP0012,Mina,Tamang,Other,47,Biratnagar,Marketing,Marketing Executive,Contract,...,Inactive,PhD,mina.tamang12@company.com,9893320274.0,9847644351.0,Sanjay Sharma,PMP,Flexible,Average,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
71,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
72,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
73,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No
74,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q22. LIKE Operator\n**Find employees whose last_name starts with S.**

In [47]:
query_22 = """
SELECT * FROM employees
WHERE last_name LIKE 'S%';
"""
run_query(query_22)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,28,EMP0028,Amit,Sharma,Female,31,Pokhara,HR,HR Manager,Part-Time,...,On Leave,PhD,amit.sharma28@company.com,9813798947.0,9846356183.0,Sanjay Sharma,Power BI,Evening,Good,No
1,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
2,42,EMP0042,Pratigya,Sharma,Female,56,Lalitpur,Operations,Operations Officer,Part-Time,...,Inactive,Bachelor,pratigya.sharma42@company.com,9897299598.0,9897403192.0,Rita Thapa,Power BI,Evening,Excellent,Yes
3,43,EMP0043,Amit,Sharma,Female,23,Chitwan,Finance,Accountant,Intern,...,Active,Master,amit.sharma43@company.com,9817143479.0,9882701840.0,Mina Rai,AWS,Day,Excellent,No
4,44,EMP0044,Suman,Shrestha,Male,49,Kathmandu,Marketing,Marketing Executive,Contract,...,Active,Master,suman.shrestha44@company.com,9896723552.0,9897990221.0,Prakash Karki,Python,Flexible,Average,Yes
5,49,EMP0049,Roshani,Sharma,Other,41,Chitwan,Analytics,BI Analyst,Contract,...,On Leave,Diploma,roshani.sharma49@company.com,9892734355.0,9883696064.0,Rita Thapa,AWS,Day,Excellent,No
6,60,EMP0060,Roshani,Shrestha,Other,27,Butwal,IT,Data Engineer,Part-Time,...,Active,Diploma,roshani.shrestha60@company.com,9864888845.0,9859795676.0,Prakash Karki,PMP,Evening,Excellent,No
7,63,EMP0063,Suman,Shrestha,Other,55,Kathmandu,Sales,Sales Manager,Contract,...,Inactive,Diploma,suman.shrestha63@company.com,9836063000.0,9884127728.0,Rita Thapa,AWS,Evening,Excellent,Yes
8,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
9,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
10,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
11,102,EMP0102,Ramesh,Sharma,Male,57,Lalitpur,Operations,Project Coordinator,Full-Time,...,On Leave,PhD,ramesh.sharma102@company.com,9828945559.0,NaN,Prakash Karki,AWS,Flexible,Average,Yes
12,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
13,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No

### Q23. LIKE Operator\n**Find employees whose job_title contains the word Analyst.**

In [48]:
query_23 = """
SELECT * FROM employees
WHERE job_title LIKE '%Analyst%';
"""
run_query(query_23)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
1,18,EMP0018,Mina,Adhikari,Male,41,Butwal,Finance,Financial Analyst,Contract,...,On Leave,Master,mina.adhikari18@company.com,9830246318.0,9863562849.0,Amit Pandey,None,Evening,Good,No
2,30,EMP0030,Anish,Basnet,Male,53,Pokhara,Analytics,Data Analyst,Part-Time,...,On Leave,Diploma,anish.basnet30@company.com,9852672583.0,9898658609.0,Mina Rai,AWS,Flexible,Excellent,Yes
3,32,EMP0032,Pratigya,Karki,Male,57,Pokhara,Analytics,Data Analyst,Full-Time,...,Active,Master,pratigya.karki32@company.com,9882520415.0,9857868867.0,Prakash Karki,Python,Evening,Average,No
4,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
5,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
6,48,EMP0048,Ramesh,Rai,Other,49,Kathmandu,Analytics,Data Analyst,Part-Time,...,Inactive,PhD,ramesh.rai48@company.com,9832568994.0,9823644673.0,Prakash Karki,PMP,Flexible,Good,Yes
7,49,EMP0049,Roshani,Sharma,Other,41,Chitwan,Analytics,BI Analyst,Contract,...,On Leave,Diploma,roshani.sharma49@company.com,9892734355.0,9883696064.0,Rita Thapa,AWS,Day,Excellent,No
8,51,EMP0051,Nabin,Poudel,Other,60,Lalitpur,Analytics,Data Analyst,Intern,...,On Leave,Bachelor,nabin.poudel51@company.com,9867614636.0,NaN,Amit Pandey,Power BI,Day,Excellent,Yes
9,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
10,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
11,69,EMP0069,Binita,Basnet,Male,59,Butwal,Analytics,Data Analyst,Intern,...,On Leave,PhD,binita.basnet69@company.com,NaN,9863222909.0,Rita Thapa,Power BI,Flexible,Excellent,No
12,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
13,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
14,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
15,86,EMP0086,Pratigya,Thapa,Female,21,Chitwan,Finance,Financial Analyst,Part-Time,...,Active,Diploma,pratigya.thapa86@company.com,9878479872.0,9838354028.0,Sanjay Sharma,AWS,Flexible,Average,Yes
16,87,EMP0087,Kiran,Tamang,Male,29,Bhaktapur,Analytics,Data Analyst,Contract,...,Inactive,Bachelor,kiran.tamang87@company.com,9875621662.0,9881447513.0,Rita Thapa,Power BI,Evening,Good,Yes
17,89,EMP0089,Pratigya,Maharjan,Male,50,Bhaktapur,Finance,Financial Analyst,Intern,...,Active,PhD,pratigya.maharjan89@company.com,9848204430.0,9887110232.0,Sanjay Sharma,Power BI,Evening,Good,Yes
18,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
19,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
20,115,EMP0115,Sanjay,Rai,Other,39,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,PhD,sanjay.rai115@company.com,NaN,9830089243.0,Rita Thapa,SQL,Day,Excellent,No
21,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No
22,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q24. LIKE Operator\n**Find employees whose email ends with @company.com.**

In [49]:
query_24 = """
SELECT * FROM employees
WHERE email LIKE '%@company.com';
"""
run_query(query_24)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
4,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
139,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
140,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
141,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No
142,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q25. IN Operator\n**Find employees working in Kathmandu, Pokhara, or Lalitpur.**

In [50]:
query_25 = """
SELECT * FROM employees
WHERE city IN ('Kathmandu', 'Pokhara', 'Lalitpur');
"""
run_query(query_25)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
4,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
59,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
60,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
61,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
62,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q26. IN Operator\n**Find employees in the IT, Analytics, or Finance departments.**

In [51]:
query_26 = """
SELECT * FROM employees
WHERE department IN ('IT', 'Analytics', 'Finance');
"""
run_query(query_26)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No
66,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
67,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
68,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No
69,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q27. IN Operator\n**Find employees with employment_type Full-Time or Contract.**

In [52]:
query_27 = """
SELECT * FROM employees
WHERE employment_type IN ('Full-Time', 'Contract');
"""
run_query(query_27)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
4,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
73,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
74,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
75,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
76,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q28. IN Operator\n**Find employees whose education_level is Bachelor, Master, or PhD.**

In [53]:
query_28 = """
SELECT * FROM employees
WHERE education_level IN ('Bachelor', 'Master', 'PhD');
"""
run_query(query_28)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
1,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
2,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
3,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
114,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
115,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
116,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No
117,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q29. BETWEEN Operator\n**Find employees aged between 25 and 40.**

In [54]:
query_29 = """
SELECT * FROM employees
WHERE age BETWEEN 25 AND 40;
"""
run_query(query_29)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
1,14,EMP0014,Rita,Poudel,Male,37,Chitwan,IT,QA Engineer,Full-Time,...,On Leave,PhD,rita.poudel14@company.com,9887373976.0,9857017385.0,Amit Pandey,AWS,Flexible,Excellent,No
2,15,EMP0015,Nabin,Maharjan,Other,28,Butwal,Marketing,Marketing Executive,Contract,...,On Leave,PhD,nabin.maharjan15@company.com,9847773020.0,9854365408.0,Sanjay Sharma,AWS,Flexible,Excellent,No
3,16,EMP0016,Suman,Khatri,Male,28,Bhaktapur,HR,Recruiter,Intern,...,Active,Diploma,suman.khatri16@company.com,9867011675.0,9887594913.0,Sanjay Sharma,Python,Flexible,Excellent,Yes
4,21,EMP0021,Sneha,Rai,Male,39,Butwal,HR,HR Manager,Part-Time,...,Inactive,Bachelor,sneha.rai21@company.com,9896943854.0,9874426133.0,Amit Pandey,Power BI,Day,Good,Yes
5,22,EMP0022,Aarav,Maharjan,Female,28,Butwal,HR,HR Manager,Full-Time,...,On Leave,PhD,aarav.maharjan22@company.com,9824263193.0,9853794068.0,Rita Thapa,Power BI,Flexible,Good,Yes
6,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
7,28,EMP0028,Amit,Sharma,Female,31,Pokhara,HR,HR Manager,Part-Time,...,On Leave,PhD,amit.sharma28@company.com,9813798947.0,9846356183.0,Sanjay Sharma,Power BI,Evening,Good,No
8,31,EMP0031,Sabina,Gurung,Other,34,Bhaktapur,IT,QA Engineer,Part-Time,...,Active,Master,sabina.gurung31@company.com,9885012599.0,9853722847.0,Rita Thapa,AWS,Flexible,Excellent,Yes
9,33,EMP0033,Aarav,Rai,Female,35,Kathmandu,Sales,Sales Executive,Contract,...,Inactive,PhD,aarav.rai33@company.com,9878214548.0,9815405350.0,Rita Thapa,Power BI,Evening,Excellent,Yes
10,34,EMP0034,Binita,Poudel,Female,26,Chitwan,Sales,Sales Manager,Intern,...,On Leave,PhD,binita.poudel34@company.com,9838549945.0,NaN,Mina Rai,AWS,Flexible,Excellent,No
11,37,EMP0037,Kusum,Sharma,Other,26,Kathmandu,Analytics,Data Analyst,Intern,...,Inactive,Bachelor,kusum.sharma37@company.com,9849830184.0,9814996960.0,Prakash Karki,SQL,Evening,Average,No
12,40,EMP0040,Aarav,Pandey,Male,34,Chitwan,Sales,Business Development Officer,Part-Time,...,Inactive,Bachelor,aarav.pandey40@company.com,9867943072.0,9887892505.0,Prakash Karki,SQL,Flexible,Good,Yes
13,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
14,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
15,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
16,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
17,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
18,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
19,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
20,59,EMP0059,Ramesh,Rai,Other,37,Chitwan,Finance,Finance Officer,Full-Time,...,On Leave,Master,ramesh.rai59@company.com,9882437717.0,9871221053.0,Amit Pandey,SQL,Day,Good,Yes
21,60,EMP0060,Roshani,Shrestha,Other,27,Butwal,IT,Data Engineer,Part-Time,...,Active,Diploma,roshani.shrestha60@company.com,9864888845.0,9859795676.0,Prakash Karki,PMP,Evening,Excellent,No
22,61,EMP0061,Deepak,Adhikari,Female,31,Bhaktapur,Operations,Operations Officer,Contract,...,Inactive,Diploma,deepak.adhikari61@company.com,9810112314.0,9848578148.0,Rita Thapa,SQL,Flexible,Average,Yes
23,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
24,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
25,70,EMP0070,Anish,Poudel,Female,33,Lalitpur,Sales,Business Development Officer,Contract,...,Inactive,Bachelor,anish.poudel70@company.com,9864526378.0,9872613862.0,Amit Pandey,Power BI,Flexible,Excellent,No
26,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
27,75,EMP0075,Kiran,Tamang,Female,26,Kathmandu,Marketing,Content Specialist,Part-Time,...,On Leave,Master,kiran.tamang75@company.com,9810752947.0,9894539529.0,Prakash Karki,Python,Evening,Excellent,No
28,77,EMP0077,Roshani,Lama,Other,31,Butwal,Sales,Sales Executive,Intern,...,Active,PhD,roshani.lama77@company.com,9818242695.0,9827301329.0,Mina Rai,Power BI,Flexible,Excellent,Yes
29,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
30,87,EMP0087,Kiran,Tamang,Male,29,Bhaktapur,Analytics,Data Analyst,Contract,...,Inactive,Bachelor,kiran.tamang87@company.com,9875621662.0,9881447513.0,Rita Thapa,Power BI,Evening,Good,Yes
31,91,EMP0091,Kiran,Poudel,Other,29,Lalitpur,Sales,Business Development Officer,Full-Time,...,On Leave,Master,kiran.poudel91@company.com,9820708628.0,9864900957.0,Prakash Karki,None,Day,Average,Yes
32,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
33,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
34,98,EMP0098,Amit,Karki,Other,39,Lalitpur,Finance,Finance Officer,Contract,...,Active,PhD,amit.karki98@company.com,9816172851.0,9813752892.0,Prakash Karki,Power BI,Flexible,Excellent,Yes
35,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
36,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
37,115,EMP0115,Sanjay,Rai,Other,39,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,PhD,sanjay.rai115@company.com,NaN,9830089243.0,Rita Thapa,SQL,Day,Excellent,No
38,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
39,120,EMP0120,Amit,Poudel,Female,31,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,amit.poudel120@company.com,9884589166.0,9869481985.0,Rita Thapa,Python,Evening,Average,Yes
40,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
41,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
42,132,EMP0132,Amit,KC,Other,31,Butwal,Finance,Finance Officer,Full-Time,...,On Leave,Master,amit.kc132@company.com,9825304867.0,9883974314.0,Mina Rai,AWS,Evening,Average,No
43,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
44,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
45,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No
46,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
47,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
48,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
49,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
50,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
51,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
52,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q30. BETWEEN Operator\n**Find employees whose monthly_salary is between 80000 and 150000.**

In [55]:
query_30 = """
SELECT * FROM employees
WHERE monthly_salary BETWEEN 80000 AND 150000;
"""
run_query(query_30)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,11,EMP0011,Nisha,Thapa,Male,43,Bhaktapur,Marketing,Marketing Executive,Contract,...,Active,Master,nisha.thapa11@company.com,9833751475.0,9853726695.0,Mina Rai,PMP,Day,Excellent,Yes
3,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
4,17,EMP0017,Suman,Khatri,Female,55,Biratnagar,HR,HR Manager,Full-Time,...,Active,Bachelor,suman.khatri17@company.com,9845408799.0,NaN,Mina Rai,AWS,Flexible,Average,No
5,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
6,21,EMP0021,Sneha,Rai,Male,39,Butwal,HR,HR Manager,Part-Time,...,Inactive,Bachelor,sneha.rai21@company.com,9896943854.0,9874426133.0,Amit Pandey,Power BI,Day,Good,Yes
7,24,EMP0024,Deepak,Maharjan,Female,52,Bhaktapur,Finance,Finance Officer,Part-Time,...,On Leave,PhD,deepak.maharjan24@company.com,9889170107.0,9861221192.0,Mina Rai,Python,Evening,Excellent,No
8,25,EMP0025,Pratigya,Poudel,Other,49,Bhaktapur,Finance,Accountant,Full-Time,...,Inactive,PhD,pratigya.poudel25@company.com,9849388796.0,9887093109.0,Prakash Karki,Power BI,Flexible,Good,No
9,29,EMP0029,Sanjay,Rai,Male,52,Chitwan,Sales,Business Development Officer,Intern,...,On Leave,Master,sanjay.rai29@company.com,9872561166.0,9836673639.0,Prakash Karki,AWS,Flexible,Excellent,No
10,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
11,43,EMP0043,Amit,Sharma,Female,23,Chitwan,Finance,Accountant,Intern,...,Active,Master,amit.sharma43@company.com,9817143479.0,9882701840.0,Mina Rai,AWS,Day,Excellent,No
12,44,EMP0044,Suman,Shrestha,Male,49,Kathmandu,Marketing,Marketing Executive,Contract,...,Active,Master,suman.shrestha44@company.com,9896723552.0,9897990221.0,Prakash Karki,Python,Flexible,Average,Yes
13,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
14,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
15,48,EMP0048,Ramesh,Rai,Other,49,Kathmandu,Analytics,Data Analyst,Part-Time,...,Inactive,PhD,ramesh.rai48@company.com,9832568994.0,9823644673.0,Prakash Karki,PMP,Flexible,Good,Yes
16,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
17,51,EMP0051,Nabin,Poudel,Other,60,Lalitpur,Analytics,Data Analyst,Intern,...,On Leave,Bachelor,nabin.poudel51@company.com,9867614636.0,NaN,Amit Pandey,Power BI,Day,Excellent,Yes
18,52,EMP0052,Sanjay,Lama,Male,46,Kathmandu,HR,Recruiter,Contract,...,Inactive,Bachelor,sanjay.lama52@company.com,9825693263.0,9839171865.0,Sanjay Sharma,None,Evening,Excellent,No
19,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
20,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
21,59,EMP0059,Ramesh,Rai,Other,37,Chitwan,Finance,Finance Officer,Full-Time,...,On Leave,Master,ramesh.rai59@company.com,9882437717.0,9871221053.0,Amit Pandey,SQL,Day,Good,Yes
22,63,EMP0063,Suman,Shrestha,Other,55,Kathmandu,Sales,Sales Manager,Contract,...,Inactive,Diploma,suman.shrestha63@company.com,9836063000.0,9884127728.0,Rita Thapa,AWS,Evening,Excellent,Yes
23,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
24,69,EMP0069,Binita,Basnet,Male,59,Butwal,Analytics,Data Analyst,Intern,...,On Leave,PhD,binita.basnet69@company.com,NaN,9863222909.0,Rita Thapa,Power BI,Flexible,Excellent,No
25,70,EMP0070,Anish,Poudel,Female,33,Lalitpur,Sales,Business Development Officer,Contract,...,Inactive,Bachelor,anish.poudel70@company.com,9864526378.0,9872613862.0,Amit Pandey,Power BI,Flexible,Excellent,No
26,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
27,79,EMP0079,Runa,Poudel,Other,54,Biratnagar,Marketing,Marketing Executive,Intern,...,On Leave,Master,runa.poudel79@company.com,9825926241.0,9871094430.0,Prakash Karki,None,Flexible,Good,No
28,88,EMP0088,Pratigya,KC,Other,54,Bhaktapur,Finance,Accountant,Contract,...,Inactive,Diploma,pratigya.kc88@company.com,9895239113.0,9831021022.0,Sanjay Sharma,PMP,Evening,Good,Yes
29,89,EMP0089,Pratigya,Maharjan,Male,50,Bhaktapur,Finance,Financial Analyst,Intern,...,Active,PhD,pratigya.maharjan89@company.com,9848204430.0,9887110232.0,Sanjay Sharma,Power BI,Evening,Good,Yes
30,100,EMP0100,Roshani,Maharjan,Other,42,Biratnagar,Sales,Sales Executive,Full-Time,...,Active,Master,roshani.maharjan100@company.com,9899824730.0,9843196434.0,Prakash Karki,PMP,Evening,Good,Yes
31,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
32,107,EMP0107,Roshani,Rai,Female,45,Biratnagar,HR,Recruiter,Full-Time,...,Active,PhD,roshani.rai107@company.com,9846019197.0,9883539296.0,Amit Pandey,AWS,Flexible,Good,No
33,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
34,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No
35,114,EMP0114,Aarya,Lama,Other,47,Kathmandu,Analytics,Data Scientist,Part-Time,...,Inactive,Bachelor,None,9838411370.0,9836421875.0,Prakash Karki,AWS,Flexible,Good,No
36,115,EMP0115,Sanjay,Rai,Other,39,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,PhD,sanjay.rai115@company.com,NaN,9830089243.0,Rita Thapa,SQL,Day,Excellent,No
37,119,EMP0119,Runa,Pandey,Other,44,Lalitpur,HR,HR Officer,Contract,...,Inactive,PhD,runa.pandey119@company.com,9846081313.0,NaN,Mina Rai,AWS,Flexible,Average,Yes
38,121,EMP0121,Sanjay,Adhikari,Male,47,Pokhara,Finance,Finance Officer,Part-Time,...,On Leave,Diploma,sanjay.adhikari121@company.com,9864490608.0,9825305380.0,Mina Rai,Python,Evening,Average,Yes
39,123,EMP0123,Suman,Karki,Other,21,Biratnagar,Operations,Operations Officer,Part-Time,...,On Leave,Bachelor,suman.karki123@company.com,9864398068.0,9821959510.0,Rita Thapa,AWS,Evening,Excellent,Yes
40,125,EMP0125,Sanjay,Khatri,Male,59,Bhaktapur,Marketing,Content Specialist,Contract,...,On Leave,Diploma,sanjay.khatri125@company.com,9862985066.0,9889937760.0,Sanjay Sharma,Power BI,Flexible,Excellent,No
41,132,EMP0132,Amit,KC,Other,31,Butwal,Finance,Finance Officer,Full-Time,...,On Leave,Master,amit.kc132@company.com,9825304867.0,9883974314.0,Mina Rai,AWS,Evening,Average,No
42,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
43,136,EMP0136,Prakash,Maharjan,Male,22,Pokhara,Operations,Operations Manager,Full-Time,...,On Leave,Master,prakash.maharjan136@company.com,9846381299.0,NaN,Sanjay Sharma,Python,Day,Good,Yes
44,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q31. BETWEEN Operator\n**Find employees with performance_rating between 3.5 and 4.5.**

In [56]:
query_31 = """
SELECT * FROM employees
WHERE performance_rating BETWEEN 3.5 AND 4.5;
"""
run_query(query_31)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
68,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
69,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
70,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
71,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q32. BETWEEN Operator\n**Find employees with years_experience between 3 and 10.**

In [57]:
query_32 = """
SELECT * FROM employees
WHERE years_experience BETWEEN 3 AND 10;
"""
run_query(query_32)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
3,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,144,EMP0144,Sanjay,Basnet,Male,51,Kathmandu,Finance,Finance Officer,Contract,...,Active,Bachelor,sanjay.basnet144@company.com,9885588247.0,9887236300.0,Mina Rai,PMP,Flexible,Good,No
93,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
94,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
95,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
96,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q33. BETWEEN Operator\n**Find employees who joined between 2020-01-01 and 2024-12-31.**

In [58]:
query_33 = """
SELECT * FROM employees
WHERE join_date BETWEEN '2020-01-01' AND '2024-12-31';
"""
run_query(query_33)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
1,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
2,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
3,14,EMP0014,Rita,Poudel,Male,37,Chitwan,IT,QA Engineer,Full-Time,...,On Leave,PhD,rita.poudel14@company.com,9887373976.0,9857017385.0,Amit Pandey,AWS,Flexible,Excellent,No
4,15,EMP0015,Nabin,Maharjan,Other,28,Butwal,Marketing,Marketing Executive,Contract,...,On Leave,PhD,nabin.maharjan15@company.com,9847773020.0,9854365408.0,Sanjay Sharma,AWS,Flexible,Excellent,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,137,EMP0137,Amit,Karki,Female,42,Lalitpur,Sales,Sales Executive,Contract,...,On Leave,Diploma,amit.karki137@company.com,9877977817.0,9825138757.0,Prakash Karki,SQL,Evening,Excellent,Yes
59,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
60,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
61,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
62,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q34. IS NULL / IS NOT NULL\n**Find employees whose email is NULL.**

In [59]:
query_34 = """
SELECT * FROM employees
WHERE email IS NULL;
"""
run_query(query_34)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
1,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
2,57,EMP0057,Anita,Poudel,Other,59,Bhaktapur,Finance,Finance Officer,Intern,...,Inactive,Bachelor,None,9864493103.0,9896832664.0,Prakash Karki,Power BI,Evening,Good,No
3,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
4,95,EMP0095,Mina,Karki,Female,59,Biratnagar,Marketing,Content Specialist,Intern,...,Inactive,Diploma,None,9839052337.0,9832589858.0,Rita Thapa,SQL,Flexible,Excellent,Yes
5,114,EMP0114,Aarya,Lama,Other,47,Kathmandu,Analytics,Data Scientist,Part-Time,...,Inactive,Bachelor,None,9838411370.0,9836421875.0,Prakash Karki,AWS,Flexible,Good,No
6,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes

### Q35. IS NULL / IS NOT NULL\n**Find employees whose phone is NULL.**

In [60]:
query_35 = """
SELECT * FROM employees
WHERE phone IS NULL;
"""
run_query(query_35)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

Empty DataFrame
Columns: [employee_id, employee_code, first_name, last_name, gender, age, city, department, job_title, employment_type, join_date, years_experience, monthly_salary, annual_bonus, performance_rating, projects_completed, leave_days_taken, overtime_hours, remote_worker, employment_status, education_level, email, phone, emergency_contact, manager_name, certification, work_shift, performance_category, promotion_eligible]
Index: []

[0 rows x 29 columns]

### Q36. IS NULL / IS NOT NULL\n**Find employees whose emergency_contact is NULL.**

In [61]:
query_36 = """
SELECT * FROM employees
WHERE emergency_contact IS NULL;
"""
run_query(query_36)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

Empty DataFrame
Columns: [employee_id, employee_code, first_name, last_name, gender, age, city, department, job_title, employment_type, join_date, years_experience, monthly_salary, annual_bonus, performance_rating, projects_completed, leave_days_taken, overtime_hours, remote_worker, employment_status, education_level, email, phone, emergency_contact, manager_name, certification, work_shift, performance_category, promotion_eligible]
Index: []

[0 rows x 29 columns]

### Q37. IS NULL / IS NOT NULL\n**Find employees whose certification is NULL.**

In [62]:
query_37 = """
SELECT * FROM employees
WHERE certification IS NULL;
"""
run_query(query_37)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
1,18,EMP0018,Mina,Adhikari,Male,41,Butwal,Finance,Financial Analyst,Contract,...,On Leave,Master,mina.adhikari18@company.com,9830246318.0,9863562849.0,Amit Pandey,None,Evening,Good,No
2,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
3,26,EMP0026,Nabin,Karki,Other,52,Lalitpur,IT,Software Engineer,Contract,...,Inactive,Diploma,nabin.karki26@company.com,9845843496.0,9885017167.0,Sanjay Sharma,None,Evening,Good,No
4,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
5,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
6,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
7,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
8,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
9,52,EMP0052,Sanjay,Lama,Male,46,Kathmandu,HR,Recruiter,Contract,...,Inactive,Bachelor,sanjay.lama52@company.com,9825693263.0,9839171865.0,Sanjay Sharma,None,Evening,Excellent,No
10,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
11,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
12,64,EMP0064,Bikash,Tamang,Male,51,Bhaktapur,Analytics,Data Scientist,Full-Time,...,On Leave,Master,bikash.tamang64@company.com,9856325053.0,9840377727.0,Amit Pandey,None,Evening,Good,No
13,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
14,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
15,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
16,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
17,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
18,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
19,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
20,79,EMP0079,Runa,Poudel,Other,54,Biratnagar,Marketing,Marketing Executive,Intern,...,On Leave,Master,runa.poudel79@company.com,9825926241.0,9871094430.0,Prakash Karki,None,Flexible,Good,No
21,91,EMP0091,Kiran,Poudel,Other,29,Lalitpur,Sales,Business Development Officer,Full-Time,...,On Leave,Master,kiran.poudel91@company.com,9820708628.0,9864900957.0,Prakash Karki,None,Day,Average,Yes
22,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
23,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
24,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
25,109,EMP0109,Sujan,Tamang,Male,44,Chitwan,IT,Data Engineer,Part-Time,...,Active,Diploma,sujan.tamang109@company.com,9882571368.0,9883310657.0,Sanjay Sharma,None,Day,Good,No
26,117,EMP0117,Anish,Poudel,Male,53,Lalitpur,Finance,Accountant,Part-Time,...,Inactive,Master,anish.poudel117@company.com,9861663450.0,9853848371.0,Prakash Karki,None,Day,Good,Yes
27,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
28,127,EMP0127,Prakash,Rai,Female,50,Bhaktapur,Marketing,Brand Manager,Intern,...,Inactive,Master,prakash.rai127@company.com,9871549258.0,9848005441.0,Rita Thapa,None,Day,Good,No
29,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
30,130,EMP0130,Nabin,KC,Female,41,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,nabin.kc130@company.com,9821425430.0,9828721006.0,Sanjay Sharma,None,Evening,Average,No
31,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
32,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
33,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
34,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes

### Q38. IS NULL / IS NOT NULL\n**Find employees whose email is NOT NULL AND phone is NOT NULL.**

In [63]:
query_38 = """
SELECT * FROM employees
WHERE email IS NOT NULL AND phone IS NOT NULL;
"""
run_query(query_38)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
4,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
139,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
140,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
141,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No
142,150,EMP0150,Kiran,Khatri,Male,52,Kathmandu,Finance,Accountant,Part-Time,...,Active,PhD,kiran.khatri150@company.com,9822925352.0,9870724787.0,Sanjay Sharma,Python,Flexible,Good,No

### Q39. Mixed Challenge\n**Find Active employees from Kathmandu or Lalitpur whose salary is between 90000 and 180000.**

In [64]:
query_39 = """
SELECT * FROM employees
WHERE employment_status = 'Active'
  AND city IN ('Kathmandu', 'Lalitpur')
  AND monthly_salary BETWEEN 90000 AND 180000;
"""
run_query(query_39)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
2,53,EMP0053,Sneha,Khatri,Female,27,Kathmandu,Finance,Financial Analyst,Contract,...,Active,Master,sneha.khatri53@company.com,9875191287.0,9855752567.0,Amit Pandey,PMP,Evening,Good,Yes
3,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
4,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
5,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No

### Q40. Mixed Challenge\n**Find employees in IT or Analytics whose first_name starts with A and performance_rating is at least 4.**

In [65]:
query_40 = """
SELECT * FROM employees
WHERE department IN ('IT', 'Analytics')
  AND first_name LIKE 'A%'
  AND performance_rating >= 4;
"""
run_query(query_40)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
1,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
2,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No

### Q41. Mixed Challenge\n**Find employees who are not Interns and have completed more than 5 projects.**

In [66]:
query_41 = """
SELECT * FROM employees
WHERE employment_type <> 'Intern'
  AND projects_completed > 5;
"""
run_query(query_41)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
3,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
4,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes
66,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
67,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
68,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes
69,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q42. Mixed Challenge\n**Find employees with NULL certification OR NULL emergency_contact.**

In [67]:
query_42 = """
SELECT * FROM employees
WHERE certification IS NULL OR emergency_contact IS NULL;
"""
run_query(query_42)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
1,18,EMP0018,Mina,Adhikari,Male,41,Butwal,Finance,Financial Analyst,Contract,...,On Leave,Master,mina.adhikari18@company.com,9830246318.0,9863562849.0,Amit Pandey,None,Evening,Good,No
2,19,EMP0019,Sabina,Adhikari,Female,51,Kathmandu,Operations,Project Coordinator,Contract,...,Inactive,PhD,None,9864804706.0,9815034008.0,Amit Pandey,None,Day,Average,Yes
3,26,EMP0026,Nabin,Karki,Other,52,Lalitpur,IT,Software Engineer,Contract,...,Inactive,Diploma,nabin.karki26@company.com,9845843496.0,9885017167.0,Sanjay Sharma,None,Evening,Good,No
4,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
5,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
6,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
7,47,EMP0047,Anish,Thapa,Female,21,Bhaktapur,IT,QA Engineer,Full-Time,...,Active,Master,anish.thapa47@company.com,9861155566.0,9895030117.0,Rita Thapa,None,Evening,Good,Yes
8,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
9,52,EMP0052,Sanjay,Lama,Male,46,Kathmandu,HR,Recruiter,Contract,...,Inactive,Bachelor,sanjay.lama52@company.com,9825693263.0,9839171865.0,Sanjay Sharma,None,Evening,Excellent,No
10,54,EMP0054,Runa,KC,Female,29,Kathmandu,Sales,Sales Manager,Part-Time,...,On Leave,Bachelor,runa.kc54@company.com,9873830505.0,9857183874.0,Mina Rai,None,Evening,Average,Yes
11,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
12,64,EMP0064,Bikash,Tamang,Male,51,Bhaktapur,Analytics,Data Scientist,Full-Time,...,On Leave,Master,bikash.tamang64@company.com,9856325053.0,9840377727.0,Amit Pandey,None,Evening,Good,No
13,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
14,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
15,68,EMP0068,Roshani,Maharjan,Female,43,Kathmandu,IT,Software Engineer,Intern,...,On Leave,Master,roshani.maharjan68@company.com,9871761686.0,NaN,Rita Thapa,None,Evening,Average,Yes
16,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
17,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
18,76,EMP0076,Anita,Tamang,Female,43,Butwal,Marketing,Marketing Executive,Intern,...,On Leave,Bachelor,None,9815670826.0,9878610191.0,Mina Rai,None,Evening,Good,Yes
19,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
20,79,EMP0079,Runa,Poudel,Other,54,Biratnagar,Marketing,Marketing Executive,Intern,...,On Leave,Master,runa.poudel79@company.com,9825926241.0,9871094430.0,Prakash Karki,None,Flexible,Good,No
21,91,EMP0091,Kiran,Poudel,Other,29,Lalitpur,Sales,Business Development Officer,Full-Time,...,On Leave,Master,kiran.poudel91@company.com,9820708628.0,9864900957.0,Prakash Karki,None,Day,Average,Yes
22,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
23,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
24,105,EMP0105,Sabina,Pandey,Other,49,Lalitpur,Finance,Financial Analyst,Intern,...,Active,Master,sabina.pandey105@company.com,9811487240.0,9851381739.0,Amit Pandey,None,Flexible,Average,No
25,109,EMP0109,Sujan,Tamang,Male,44,Chitwan,IT,Data Engineer,Part-Time,...,Active,Diploma,sujan.tamang109@company.com,9882571368.0,9883310657.0,Sanjay Sharma,None,Day,Good,No
26,117,EMP0117,Anish,Poudel,Male,53,Lalitpur,Finance,Accountant,Part-Time,...,Inactive,Master,anish.poudel117@company.com,9861663450.0,9853848371.0,Prakash Karki,None,Day,Good,Yes
27,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
28,127,EMP0127,Prakash,Rai,Female,50,Bhaktapur,Marketing,Brand Manager,Intern,...,Inactive,Master,prakash.rai127@company.com,9871549258.0,9848005441.0,Rita Thapa,None,Day,Good,No
29,128,EMP0128,Anita,Adhikari,Other,26,Biratnagar,Marketing,Content Specialist,Full-Time,...,On Leave,Master,anita.adhikari128@company.com,9851695945.0,9811013459.0,Prakash Karki,None,Day,Excellent,No
30,130,EMP0130,Nabin,KC,Female,41,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,nabin.kc130@company.com,9821425430.0,9828721006.0,Sanjay Sharma,None,Evening,Average,No
31,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
32,142,EMP0142,Anish,Thapa,Female,48,Kathmandu,Marketing,Marketing Executive,Part-Time,...,On Leave,Master,anish.thapa142@company.com,9846384488.0,9861387040.0,Sanjay Sharma,None,Flexible,Excellent,No
33,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
34,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes

### Q43. Mixed Challenge\n**Find employees whose job_title contains Manager and whose employment_status is Active.**

In [68]:
query_43 = """
SELECT * FROM employees
WHERE job_title LIKE '%Manager%'
  AND employment_status = 'Active';
"""
run_query(query_43)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,17,EMP0017,Suman,Khatri,Female,55,Biratnagar,HR,HR Manager,Full-Time,...,Active,Bachelor,suman.khatri17@company.com,9845408799.0,NaN,Mina Rai,AWS,Flexible,Average,No
1,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
2,56,EMP0056,Sujan,Poudel,Other,59,Butwal,HR,HR Manager,Intern,...,Active,PhD,sujan.poudel56@company.com,9865486797.0,9844977265.0,Prakash Karki,Python,Flexible,Good,No
3,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
4,81,EMP0081,Aarav,Karki,Female,59,Bhaktapur,Operations,Operations Manager,Full-Time,...,Active,Master,aarav.karki81@company.com,9850081864.0,9826393507.0,Sanjay Sharma,AWS,Day,Average,Yes
5,96,EMP0096,Pratigya,Shrestha,Female,35,Biratnagar,Marketing,Brand Manager,Contract,...,Active,Master,pratigya.shrestha96@company.com,9899228205.0,9813690274.0,Prakash Karki,None,Day,Good,No
6,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
7,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No
8,126,EMP0126,Sita,Lama,Other,28,Bhaktapur,Marketing,Brand Manager,Intern,...,Active,Master,sita.lama126@company.com,9862211642.0,9852134402.0,Rita Thapa,None,Evening,Average,Yes
9,141,EMP0141,Sneha,KC,Male,28,Biratnagar,Marketing,Brand Manager,Full-Time,...,Active,PhD,sneha.kc141@company.com,9827691817.0,9854391749.0,Amit Pandey,SQL,Evening,Good,No
10,148,EMP0148,Aarav,Tamang,Other,35,Lalitpur,Sales,Sales Manager,Contract,...,Active,Bachelor,aarav.tamang148@company.com,9817882426.0,9815629239.0,Rita Thapa,Python,Day,Good,Yes

### Q44. Mixed Challenge\n**Display employees aged between 30 and 50 who work remotely and have salary above 120000.**

In [69]:
query_44 = """
SELECT * FROM employees
WHERE age BETWEEN 30 AND 50
  AND remote_worker = 'Yes'
  AND monthly_salary > 120000;
"""
run_query(query_44)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
1,18,EMP0018,Mina,Adhikari,Male,41,Butwal,Finance,Financial Analyst,Contract,...,On Leave,Master,mina.adhikari18@company.com,9830246318.0,9863562849.0,Amit Pandey,None,Evening,Good,No
2,21,EMP0021,Sneha,Rai,Male,39,Butwal,HR,HR Manager,Part-Time,...,Inactive,Bachelor,sneha.rai21@company.com,9896943854.0,9874426133.0,Amit Pandey,Power BI,Day,Good,Yes
3,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
4,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
5,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
6,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
7,73,EMP0073,Anish,Lama,Female,44,Kathmandu,Marketing,Marketing Executive,Intern,...,Active,Bachelor,anish.lama73@company.com,9894059886.0,9852075442.0,Sanjay Sharma,None,Flexible,Excellent,No
8,77,EMP0077,Roshani,Lama,Other,31,Butwal,Sales,Sales Executive,Intern,...,Active,PhD,roshani.lama77@company.com,9818242695.0,9827301329.0,Mina Rai,Power BI,Flexible,Excellent,Yes
9,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
10,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
11,94,EMP0094,Rahul,Pandey,Other,49,Pokhara,IT,Software Engineer,Contract,...,Active,PhD,rahul.pandey94@company.com,9873692578.0,9868982824.0,Mina Rai,Power BI,Day,Good,No
12,97,EMP0097,Prakash,KC,Female,41,Biratnagar,HR,Recruiter,Contract,...,On Leave,Bachelor,prakash.kc97@company.com,9853788620.0,9830192982.0,Prakash Karki,Power BI,Day,Excellent,No
13,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
14,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
15,107,EMP0107,Roshani,Rai,Female,45,Biratnagar,HR,Recruiter,Full-Time,...,Active,PhD,roshani.rai107@company.com,9846019197.0,9883539296.0,Amit Pandey,AWS,Flexible,Good,No
16,115,EMP0115,Sanjay,Rai,Other,39,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,PhD,sanjay.rai115@company.com,NaN,9830089243.0,Rita Thapa,SQL,Day,Excellent,No
17,118,EMP0118,Deepak,Karki,Female,31,Kathmandu,IT,Data Engineer,Full-Time,...,Inactive,Diploma,deepak.karki118@company.com,9841658224.0,9877458760.0,Rita Thapa,AWS,Day,Average,Yes
18,120,EMP0120,Amit,Poudel,Female,31,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,amit.poudel120@company.com,9884589166.0,9869481985.0,Rita Thapa,Python,Evening,Average,Yes
19,121,EMP0121,Sanjay,Adhikari,Male,47,Pokhara,Finance,Finance Officer,Part-Time,...,On Leave,Diploma,sanjay.adhikari121@company.com,9864490608.0,9825305380.0,Mina Rai,Python,Evening,Average,Yes
20,130,EMP0130,Nabin,KC,Female,41,Biratnagar,Operations,Operations Officer,Intern,...,On Leave,Master,nabin.kc130@company.com,9821425430.0,9828721006.0,Sanjay Sharma,None,Evening,Average,No
21,131,EMP0131,Rita,Pandey,Other,48,Butwal,HR,HR Officer,Contract,...,Active,Master,rita.pandey131@company.com,9867615075.0,9846545625.0,Sanjay Sharma,PMP,Flexible,Good,No
22,137,EMP0137,Amit,Karki,Female,42,Lalitpur,Sales,Sales Executive,Contract,...,On Leave,Diploma,amit.karki137@company.com,9877977817.0,9825138757.0,Prakash Karki,SQL,Evening,Excellent,Yes
23,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
24,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q45. Mixed Challenge\n**Calculate annual_salary and total_compensation for employees in Finance, IT, and Analytics.**

In [70]:
query_45 = """
SELECT employee_id, first_name, department, monthly_salary,
       monthly_salary * 12 AS annual_salary,
       (monthly_salary * 12) + annual_bonus AS total_compensation
FROM employees
WHERE department IN ('Finance', 'IT', 'Analytics');
"""
run_query(query_45)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,first_name,department,monthly_salary,annual_salary,total_compensation
0,1,Prakash,IT,105000.0,1260000.0,1275750.0
1,3,Ramesh,IT,70000.0,840000.0,848400.0
2,5,Aarya,IT,200000.0,2400000.0,2424000.0
3,7,Suman,Analytics,35000.0,420000.0,423500.0
4,8,Runa,Analytics,195000.0,2340000.0,2363400.0
...,...,...,...,...,...,...
65,140,Rahul,Finance,55000.0,660000.0,666600.0
66,143,Ramesh,IT,220000.0,2640000.0,2657600.0
67,144,Sanjay,Finance,67500.0,810000.0,813375.0
68,149,Sabina,Analytics,150000.0,1800000.0,1812000.0
69,150,Kiran,Finance,37500.0,450000.0,451875.0

### Q46. Mixed Challenge\n**Find employees whose promotion_eligible = Yes AND performance_category = Excellent.**

In [71]:
query_46 = """
SELECT * FROM employees
WHERE promotion_eligible = 'Yes'
  AND performance_category = 'Excellent';
"""
run_query(query_46)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,3,EMP0003,Ramesh,Maharjan,Other,58,Bhaktapur,IT,QA Engineer,Full-Time,...,Inactive,Master,ramesh.maharjan3@company.com,9880417695.0,9844714533.0,Mina Rai,Power BI,Day,Excellent,Yes
1,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
2,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
3,9,EMP0009,Nisha,Pandey,Other,41,Pokhara,Operations,Operations Manager,Full-Time,...,Inactive,Diploma,nisha.pandey9@company.com,9893663689.0,9855153375.0,Mina Rai,Power BI,Day,Excellent,Yes
4,11,EMP0011,Nisha,Thapa,Male,43,Bhaktapur,Marketing,Marketing Executive,Contract,...,Active,Master,nisha.thapa11@company.com,9833751475.0,9853726695.0,Mina Rai,PMP,Day,Excellent,Yes
5,16,EMP0016,Suman,Khatri,Male,28,Bhaktapur,HR,Recruiter,Intern,...,Active,Diploma,suman.khatri16@company.com,9867011675.0,9887594913.0,Sanjay Sharma,Python,Flexible,Excellent,Yes
6,30,EMP0030,Anish,Basnet,Male,53,Pokhara,Analytics,Data Analyst,Part-Time,...,On Leave,Diploma,anish.basnet30@company.com,9852672583.0,9898658609.0,Mina Rai,AWS,Flexible,Excellent,Yes
7,31,EMP0031,Sabina,Gurung,Other,34,Bhaktapur,IT,QA Engineer,Part-Time,...,Active,Master,sabina.gurung31@company.com,9885012599.0,9853722847.0,Rita Thapa,AWS,Flexible,Excellent,Yes
8,33,EMP0033,Aarav,Rai,Female,35,Kathmandu,Sales,Sales Executive,Contract,...,Inactive,PhD,aarav.rai33@company.com,9878214548.0,9815405350.0,Rita Thapa,Power BI,Evening,Excellent,Yes
9,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
10,42,EMP0042,Pratigya,Sharma,Female,56,Lalitpur,Operations,Operations Officer,Part-Time,...,Inactive,Bachelor,pratigya.sharma42@company.com,9897299598.0,9897403192.0,Rita Thapa,Power BI,Evening,Excellent,Yes
11,51,EMP0051,Nabin,Poudel,Other,60,Lalitpur,Analytics,Data Analyst,Intern,...,On Leave,Bachelor,nabin.poudel51@company.com,9867614636.0,NaN,Amit Pandey,Power BI,Day,Excellent,Yes
12,63,EMP0063,Suman,Shrestha,Other,55,Kathmandu,Sales,Sales Manager,Contract,...,Inactive,Diploma,suman.shrestha63@company.com,9836063000.0,9884127728.0,Rita Thapa,AWS,Evening,Excellent,Yes
13,65,EMP0065,Roshani,Shrestha,Female,34,Biratnagar,Analytics,Data Analyst,Full-Time,...,On Leave,Diploma,roshani.shrestha65@company.com,9848110898.0,9850083036.0,Prakash Karki,None,Day,Excellent,Yes
14,72,EMP0072,Amit,Sharma,Other,38,Kathmandu,Finance,Finance Officer,Part-Time,...,On Leave,PhD,amit.sharma72@company.com,9871713926.0,9879496093.0,Prakash Karki,None,Evening,Excellent,Yes
15,77,EMP0077,Roshani,Lama,Other,31,Butwal,Sales,Sales Executive,Intern,...,Active,PhD,roshani.lama77@company.com,9818242695.0,9827301329.0,Mina Rai,Power BI,Flexible,Excellent,Yes
16,82,EMP0082,Rahul,Thapa,Female,45,Kathmandu,Finance,Finance Officer,Intern,...,Inactive,Bachelor,rahul.thapa82@company.com,9814408661.0,9896296613.0,Mina Rai,PMP,Day,Excellent,Yes
17,83,EMP0083,Pooja,KC,Female,24,Pokhara,Sales,Sales Manager,Contract,...,On Leave,PhD,pooja.kc83@company.com,9854881134.0,9837460878.0,Amit Pandey,AWS,Evening,Excellent,Yes
18,85,EMP0085,Pooja,Khatri,Female,59,Biratnagar,Sales,Sales Executive,Part-Time,...,Active,PhD,pooja.khatri85@company.com,9820233067.0,NaN,Mina Rai,SQL,Day,Excellent,Yes
19,92,EMP0092,Rita,Thapa,Female,32,Kathmandu,Sales,Business Development Officer,Intern,...,On Leave,Bachelor,rita.thapa92@company.com,NaN,9821869890.0,Amit Pandey,SQL,Day,Excellent,Yes
20,95,EMP0095,Mina,Karki,Female,59,Biratnagar,Marketing,Content Specialist,Intern,...,Inactive,Diploma,None,9839052337.0,9832589858.0,Rita Thapa,SQL,Flexible,Excellent,Yes
21,98,EMP0098,Amit,Karki,Other,39,Lalitpur,Finance,Finance Officer,Contract,...,Active,PhD,amit.karki98@company.com,9816172851.0,9813752892.0,Prakash Karki,Power BI,Flexible,Excellent,Yes
22,99,EMP0099,Binita,Karki,Male,36,Butwal,IT,QA Engineer,Intern,...,Active,Bachelor,binita.karki99@company.com,9878656923.0,9819618499.0,Mina Rai,PMP,Day,Excellent,Yes
23,101,EMP0101,Mina,Lama,Female,31,Butwal,Analytics,BI Analyst,Part-Time,...,Active,Diploma,mina.lama101@company.com,9891035867.0,9854449566.0,Amit Pandey,Python,Flexible,Excellent,Yes
24,103,EMP0103,Ramesh,Tamang,Other,44,Pokhara,Operations,Project Coordinator,Full-Time,...,Inactive,PhD,ramesh.tamang103@company.com,9820182234.0,9879899607.0,Mina Rai,Power BI,Evening,Excellent,Yes
25,123,EMP0123,Suman,Karki,Other,21,Biratnagar,Operations,Operations Officer,Part-Time,...,On Leave,Bachelor,suman.karki123@company.com,9864398068.0,9821959510.0,Rita Thapa,AWS,Evening,Excellent,Yes
26,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
27,135,EMP0135,Bikash,Rai,Other,57,Butwal,Operations,Operations Officer,Contract,...,Inactive,PhD,bikash.rai135@company.com,9855378650.0,9845380680.0,Prakash Karki,PMP,Day,Excellent,Yes
28,137,EMP0137,Amit,Karki,Female,42,Lalitpur,Sales,Sales Executive,Contract,...,On Leave,Diploma,amit.karki137@company.com,9877977817.0,9825138757.0,Prakash Karki,SQL,Evening,Excellent,Yes
29,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
30,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
31,145,EMP0145,Anita,Maharjan,Male,27,Bhaktapur,HR,Recruiter,Part-Time,...,Active,Diploma,anita.maharjan145@company.com,9814711886.0,9824351698.0,Prakash Karki,None,Day,Excellent,Yes

### Q47. Mixed Challenge\n**Find employees with overtime_hours between 20 and 60 and leave_days_taken less than 15.**

In [72]:
query_47 = """
SELECT * FROM employees
WHERE overtime_hours BETWEEN 20 AND 60
  AND leave_days_taken < 15;
"""
run_query(query_47)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,6,EMP0006,Deepak,Thapa,Female,48,Bhaktapur,Marketing,Brand Manager,Full-Time,...,Inactive,Master,deepak.thapa6@company.com,9870316750.0,9811883416.0,Rita Thapa,SQL,Day,Excellent,Yes
1,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
2,24,EMP0024,Deepak,Maharjan,Female,52,Bhaktapur,Finance,Finance Officer,Part-Time,...,On Leave,PhD,deepak.maharjan24@company.com,9889170107.0,9861221192.0,Mina Rai,Python,Evening,Excellent,No
3,27,EMP0027,Aarya,Karki,Other,35,Biratnagar,IT,Software Engineer,Full-Time,...,Active,Master,aarya.karki27@company.com,9894579966.0,9859584636.0,Amit Pandey,SQL,Evening,Excellent,No
4,34,EMP0034,Binita,Poudel,Female,26,Chitwan,Sales,Sales Manager,Intern,...,On Leave,PhD,binita.poudel34@company.com,9838549945.0,NaN,Mina Rai,AWS,Flexible,Excellent,No
5,38,EMP0038,Sanjay,Adhikari,Other,22,Kathmandu,Sales,Business Development Officer,Contract,...,Inactive,Master,None,9816199453.0,9819546277.0,Sanjay Sharma,PMP,Evening,Good,Yes
6,39,EMP0039,Roshani,Maharjan,Female,50,Bhaktapur,Finance,Financial Analyst,Full-Time,...,Inactive,Diploma,roshani.maharjan39@company.com,9843449924.0,9889951966.0,Mina Rai,None,Flexible,Good,No
7,40,EMP0040,Aarav,Pandey,Male,34,Chitwan,Sales,Business Development Officer,Part-Time,...,Inactive,Bachelor,aarav.pandey40@company.com,9867943072.0,9887892505.0,Prakash Karki,SQL,Flexible,Good,Yes
8,41,EMP0041,Anish,Adhikari,Female,31,Chitwan,Sales,Sales Manager,Contract,...,Active,PhD,anish.adhikari41@company.com,9836393021.0,9816860253.0,Rita Thapa,AWS,Day,Excellent,Yes
9,45,EMP0045,Pratigya,Pandey,Other,30,Lalitpur,Analytics,Data Scientist,Contract,...,Active,Bachelor,pratigya.pandey45@company.com,9894458990.0,9866187470.0,Mina Rai,None,Flexible,Good,Yes
10,46,EMP0046,Ramesh,Maharjan,Male,36,Chitwan,IT,Software Engineer,Part-Time,...,Inactive,Diploma,ramesh.maharjan46@company.com,NaN,9833557996.0,Sanjay Sharma,None,Day,Average,No
11,48,EMP0048,Ramesh,Rai,Other,49,Kathmandu,Analytics,Data Analyst,Part-Time,...,Inactive,PhD,ramesh.rai48@company.com,9832568994.0,9823644673.0,Prakash Karki,PMP,Flexible,Good,Yes
12,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
13,55,EMP0055,Anita,Tamang,Other,31,Kathmandu,Marketing,Brand Manager,Contract,...,On Leave,Diploma,anita.tamang55@company.com,9858975357.0,9820174959.0,Rita Thapa,Power BI,Flexible,Average,No
14,62,EMP0062,Prakash,Thapa,Female,39,Lalitpur,HR,HR Manager,Part-Time,...,Active,PhD,prakash.thapa62@company.com,9859264105.0,9887444334.0,Sanjay Sharma,None,Evening,Excellent,No
15,67,EMP0067,Mina,Tamang,Female,44,Biratnagar,Operations,Operations Manager,Full-Time,...,On Leave,Master,mina.tamang67@company.com,9868167933.0,9872507834.0,Sanjay Sharma,None,Flexible,Good,No
16,69,EMP0069,Binita,Basnet,Male,59,Butwal,Analytics,Data Analyst,Intern,...,On Leave,PhD,binita.basnet69@company.com,NaN,9863222909.0,Rita Thapa,Power BI,Flexible,Excellent,No
17,71,EMP0071,Sneha,Karki,Other,50,Kathmandu,Analytics,Data Scientist,Part-Time,...,Active,PhD,sneha.karki71@company.com,9826061271.0,9847600699.0,Sanjay Sharma,SQL,Flexible,Good,Yes
18,74,EMP0074,Aarya,Gurung,Other,59,Bhaktapur,Analytics,BI Analyst,Full-Time,...,On Leave,Diploma,aarya.gurung74@company.com,9814857511.0,9851846762.0,Rita Thapa,PMP,Day,Excellent,No
19,78,EMP0078,Sunita,Poudel,Male,59,Kathmandu,Analytics,BI Analyst,Intern,...,Active,PhD,sunita.poudel78@company.com,9844867731.0,9883134170.0,Prakash Karki,None,Day,Good,No
20,85,EMP0085,Pooja,Khatri,Female,59,Biratnagar,Sales,Sales Executive,Part-Time,...,Active,PhD,pooja.khatri85@company.com,9820233067.0,NaN,Mina Rai,SQL,Day,Excellent,Yes
21,88,EMP0088,Pratigya,KC,Other,54,Bhaktapur,Finance,Accountant,Contract,...,Inactive,Diploma,pratigya.kc88@company.com,9895239113.0,9831021022.0,Sanjay Sharma,PMP,Evening,Good,Yes
22,89,EMP0089,Pratigya,Maharjan,Male,50,Bhaktapur,Finance,Financial Analyst,Intern,...,Active,PhD,pratigya.maharjan89@company.com,9848204430.0,9887110232.0,Sanjay Sharma,Power BI,Evening,Good,Yes
23,100,EMP0100,Roshani,Maharjan,Other,42,Biratnagar,Sales,Sales Executive,Full-Time,...,Active,Master,roshani.maharjan100@company.com,9899824730.0,9843196434.0,Prakash Karki,PMP,Evening,Good,Yes
24,104,EMP0104,Sanjay,Karki,Female,44,Kathmandu,Finance,Accountant,Full-Time,...,On Leave,Master,sanjay.karki104@company.com,9898125015.0,9838059497.0,Prakash Karki,None,Flexible,Excellent,No
25,110,EMP0110,Sabina,Shrestha,Other,52,Kathmandu,Sales,Sales Manager,Part-Time,...,Active,Bachelor,sabina.shrestha110@company.com,9828642937.0,9811754847.0,Rita Thapa,SQL,Day,Good,No
26,111,EMP0111,Aarya,Tamang,Female,54,Butwal,Finance,Accountant,Part-Time,...,Inactive,Master,aarya.tamang111@company.com,9888759129.0,9821730882.0,Mina Rai,SQL,Flexible,Average,Yes
27,112,EMP0112,Sabina,Shrestha,Male,51,Biratnagar,HR,HR Manager,Intern,...,Active,Diploma,sabina.shrestha112@company.com,9853529432.0,9887182438.0,Sanjay Sharma,Python,Evening,Good,No
28,113,EMP0113,Anish,Rai,Female,50,Pokhara,Marketing,Brand Manager,Intern,...,On Leave,PhD,anish.rai113@company.com,9875495240.0,9874249204.0,Amit Pandey,SQL,Day,Good,Yes
29,117,EMP0117,Anish,Poudel,Male,53,Lalitpur,Finance,Accountant,Part-Time,...,Inactive,Master,anish.poudel117@company.com,9861663450.0,9853848371.0,Prakash Karki,None,Day,Good,Yes
30,119,EMP0119,Runa,Pandey,Other,44,Lalitpur,HR,HR Officer,Contract,...,Inactive,PhD,runa.pandey119@company.com,9846081313.0,NaN,Mina Rai,AWS,Flexible,Average,Yes
31,124,EMP0124,Mina,Tamang,Other,51,Biratnagar,Marketing,Content Specialist,Part-Time,...,Inactive,Master,mina.tamang124@company.com,9885442780.0,9821786936.0,Prakash Karki,PMP,Day,Average,Yes
32,125,EMP0125,Sanjay,Khatri,Male,59,Bhaktapur,Marketing,Content Specialist,Contract,...,On Leave,Diploma,sanjay.khatri125@company.com,9862985066.0,9889937760.0,Sanjay Sharma,Power BI,Flexible,Excellent,No
33,133,EMP0133,Aarya,Rai,Male,34,Pokhara,Finance,Finance Officer,Intern,...,On Leave,Master,None,9866873653.0,9816280106.0,Amit Pandey,Power BI,Evening,Excellent,Yes
34,138,EMP0138,Pooja,Khatri,Female,32,Kathmandu,IT,QA Engineer,Full-Time,...,Active,Master,pooja.khatri138@company.com,NaN,9814856855.0,Amit Pandey,None,Day,Excellent,Yes
35,140,EMP0140,Rahul,Poudel,Female,36,Kathmandu,Finance,Financial Analyst,Part-Time,...,Active,Master,rahul.poudel140@company.com,9835349138.0,9869524317.0,Rita Thapa,Power BI,Flexible,Excellent,No

### Q48. Mixed Challenge\n**Find employees from cities other than Kathmandu whose first_name contains the letter u.**

In [73]:
query_48 = """
SELECT * FROM employees
WHERE city <> 'Kathmandu'
  AND first_name LIKE '%u%';
"""
run_query(query_48)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,7,EMP0007,Suman,Rai,Female,43,Chitwan,Analytics,Data Scientist,Contract,...,Active,Diploma,suman.rai7@company.com,9839920845.0,9873482774.0,Amit Pandey,PMP,Flexible,Excellent,Yes
1,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
2,13,EMP0013,Runa,Rai,Other,27,Butwal,IT,Software Engineer,Contract,...,On Leave,Master,runa.rai13@company.com,9852084090.0,9847149597.0,Amit Pandey,None,Evening,Good,Yes
3,16,EMP0016,Suman,Khatri,Male,28,Bhaktapur,HR,Recruiter,Intern,...,Active,Diploma,suman.khatri16@company.com,9867011675.0,9887594913.0,Sanjay Sharma,Python,Flexible,Excellent,Yes
4,17,EMP0017,Suman,Khatri,Female,55,Biratnagar,HR,HR Manager,Full-Time,...,Active,Bachelor,suman.khatri17@company.com,9845408799.0,NaN,Mina Rai,AWS,Flexible,Average,No
5,20,EMP0020,Suman,Gurung,Other,58,Bhaktapur,IT,Data Engineer,Contract,...,On Leave,Bachelor,suman.gurung20@company.com,9824082320.0,9821480544.0,Amit Pandey,Python,Flexible,Average,Yes
6,35,EMP0035,Sujan,Pandey,Female,56,Biratnagar,Operations,Project Coordinator,Part-Time,...,On Leave,Bachelor,sujan.pandey35@company.com,9831215328.0,9825454771.0,Amit Pandey,Python,Flexible,Excellent,No
7,36,EMP0036,Sujan,Tamang,Female,46,Lalitpur,Finance,Accountant,Intern,...,Inactive,Bachelor,sujan.tamang36@company.com,9824423415.0,9829326305.0,Rita Thapa,PMP,Flexible,Average,No
8,50,EMP0050,Sujan,Lama,Female,33,Butwal,IT,QA Engineer,Contract,...,Inactive,PhD,sujan.lama50@company.com,9892119212.0,9851221953.0,Sanjay Sharma,None,Evening,Excellent,No
9,56,EMP0056,Sujan,Poudel,Other,59,Butwal,HR,HR Manager,Intern,...,Active,PhD,sujan.poudel56@company.com,9865486797.0,9844977265.0,Prakash Karki,Python,Flexible,Good,No
10,79,EMP0079,Runa,Poudel,Other,54,Biratnagar,Marketing,Marketing Executive,Intern,...,On Leave,Master,runa.poudel79@company.com,9825926241.0,9871094430.0,Prakash Karki,None,Flexible,Good,No
11,80,EMP0080,Arjun,Adhikari,Female,31,Biratnagar,Analytics,BI Analyst,Part-Time,...,On Leave,Master,arjun.adhikari80@company.com,9830715403.0,9894736966.0,Prakash Karki,Python,Flexible,Excellent,No
12,84,EMP0084,Rahul,Basnet,Female,44,Butwal,HR,Recruiter,Part-Time,...,Active,PhD,rahul.basnet84@company.com,9819744349.0,9896527602.0,Mina Rai,SQL,Day,Good,No
13,94,EMP0094,Rahul,Pandey,Other,49,Pokhara,IT,Software Engineer,Contract,...,Active,PhD,rahul.pandey94@company.com,9873692578.0,9868982824.0,Mina Rai,Power BI,Day,Good,No
14,109,EMP0109,Sujan,Tamang,Male,44,Chitwan,IT,Data Engineer,Part-Time,...,Active,Diploma,sujan.tamang109@company.com,9882571368.0,9883310657.0,Sanjay Sharma,None,Day,Good,No
15,119,EMP0119,Runa,Pandey,Other,44,Lalitpur,HR,HR Officer,Contract,...,Inactive,PhD,runa.pandey119@company.com,9846081313.0,NaN,Mina Rai,AWS,Flexible,Average,Yes
16,123,EMP0123,Suman,Karki,Other,21,Biratnagar,Operations,Operations Officer,Part-Time,...,On Leave,Bachelor,suman.karki123@company.com,9864398068.0,9821959510.0,Rita Thapa,AWS,Evening,Excellent,Yes
17,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No

### Q49. Mixed Challenge\n**Find employees with monthly_salary > 100000 OR annual_bonus > 150000.**

In [74]:
query_49 = """
SELECT * FROM employees
WHERE monthly_salary > 100000 OR annual_bonus > 150000;
"""
run_query(query_49)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,last_name,gender,age,city,department,job_title,employment_type,...,employment_status,education_level,email,phone,emergency_contact,manager_name,certification,work_shift,performance_category,promotion_eligible
0,1,EMP0001,Prakash,Adhikari,Other,53,Kathmandu,IT,Software Engineer,Contract,...,Active,Diploma,prakash.adhikari1@company.com,9869202768.0,9842203407.0,Amit Pandey,SQL,Day,Average,No
1,2,EMP0002,Prakash,Gurung,Male,46,Bhaktapur,Operations,Operations Officer,Contract,...,Active,PhD,prakash.gurung2@company.com,9884819744.0,9882217824.0,Sanjay Sharma,AWS,Evening,Good,No
2,4,EMP0004,Amit,KC,Other,51,Lalitpur,Operations,Operations Manager,Intern,...,On Leave,Diploma,amit.kc4@company.com,9843689519.0,9885134554.0,Amit Pandey,Power BI,Day,Good,No
3,5,EMP0005,Aarya,Thapa,Other,59,Kathmandu,IT,Data Engineer,Contract,...,On Leave,Bachelor,aarya.thapa5@company.com,9876727300.0,9868281295.0,Amit Pandey,PMP,Evening,Average,No
4,8,EMP0008,Runa,Maharjan,Female,58,Butwal,Analytics,BI Analyst,Contract,...,Active,Bachelor,runa.maharjan8@company.com,9824245056.0,9862257400.0,Sanjay Sharma,SQL,Flexible,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,139,EMP0139,Sujan,Gurung,Female,24,Butwal,Sales,Business Development Officer,Intern,...,Inactive,Master,sujan.gurung139@company.com,9841691465.0,9876681114.0,Rita Thapa,Power BI,Day,Average,No
93,143,EMP0143,Ramesh,Karki,Female,33,Lalitpur,IT,Data Engineer,Part-Time,...,Active,PhD,ramesh.karki143@company.com,9849486194.0,9891829050.0,Amit Pandey,None,Day,Excellent,Yes
94,146,EMP0146,Anita,Karki,Female,28,Chitwan,Operations,Operations Officer,Contract,...,Active,Master,anita.karki146@company.com,9893718200.0,9854339328.0,Sanjay Sharma,Power BI,Flexible,Average,No
95,147,EMP0147,Mina,Lama,Other,40,Biratnagar,HR,HR Officer,Full-Time,...,On Leave,Bachelor,mina.lama147@company.com,9883240890.0,9845164663.0,Mina Rai,PMP,Evening,Average,Yes
96,149,EMP0149,Sabina,KC,Male,39,Bhaktapur,Analytics,Data Analyst,Full-Time,...,Active,Bachelor,sabina.kc149@company.com,9840955018.0,9841011816.0,Prakash Karki,Power BI,Day,Excellent,No

### Q50. Mixed Challenge\n**Display employee_id, employee_code, first_name, department, monthly_salary, and monthly_salary * 12 as annual_salary for Active employees.**

In [75]:
query_50 = """
SELECT employee_id, employee_code, first_name, department, monthly_salary,
       monthly_salary * 12 AS annual_salary
FROM employees
WHERE employment_status = 'Active';
"""
run_query(query_50)

C:\Users\acer\AppData\Local\Temp\ipykernel_22692\2524898941.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn)

,employee_id,employee_code,first_name,department,monthly_salary,annual_salary
0,1,EMP0001,Prakash,IT,105000.0,1260000.0
1,2,EMP0002,Prakash,Operations,145000.0,1740000.0
2,7,EMP0007,Suman,Analytics,35000.0,420000.0
3,8,EMP0008,Runa,Analytics,195000.0,2340000.0
4,11,EMP0011,Nisha,Marketing,117500.0,1410000.0
5,16,EMP0016,Suman,HR,232500.0,2790000.0
6,17,EMP0017,Suman,HR,115000.0,1380000.0
7,23,EMP0023,Sanjay,Finance,212500.0,2550000.0
8,27,EMP0027,Aarya,IT,245000.0,2940000.0
9,31,EMP0031,Sabina,IT,197500.0,2370000.0
10,32,EMP0032,Pratigya,Analytics,247500.0,2970000.0
11,41,EMP0041,Anish,Sales,162500.0,1950000.0
12,43,EMP0043,Amit,Finance,117500.0,1410000.0
13,44,EMP0044,Suman,Marketing,87500.0,1050000.0
14,45,EMP0045,Pratigya,Analytics,90000.0,1080000.0
15,47,EMP0047,Anish,IT,80000.0,960000.0
16,53,EMP0053,Sneha,Finance,142500.0,1710000.0
17,56,EMP0056,Sujan,HR,202500.0,2430000.0
18,60,EMP0060,Roshani,IT,222500.0,2670000.0
19,62,EMP0062,Prakash,HR,67500.0,810000.0
20,71,EMP0071,Sneha,Analytics,55000.0,660000.0
21,73,EMP0073,Anish,Marketing,212500.0,2550000.0
22,77,EMP0077,Roshani,Sales,225000.0,2700000.0
23,78,EMP0078,Sunita,Analytics,127500.0,1530000.0
24,81,EMP0081,Aarav,Operations,47500.0,570000.0
25,84,EMP0084,Rahul,HR,50000.0,600000.0
26,85,EMP0085,Pooja,Sales,207500.0,2490000.0
27,86,EMP0086,Pratigya,Finance,72500.0,870000.0
28,89,EMP0089,Pratigya,Finance,105000.0,1260000.0
29,94,EMP0094,Rahul,IT,170000.0,2040000.0
30,96,EMP0096,Pratigya,Marketing,72500.0,870000.0
31,98,EMP0098,Amit,Finance,45000.0,540000.0
32,99,EMP0099,Binita,IT,152500.0,1830000.0
33,100,EMP0100,Roshani,Sales,117500.0,1410000.0
34,101,EMP0101,Mina,Analytics,210000.0,2520000.0
35,105,EMP0105,Sabina,Finance,95000.0,1140000.0
36,107,EMP0107,Roshani,HR,127500.0,1530000.0
37,109,EMP0109,Sujan,IT,240000.0,2880000.0
38,110,EMP0110,Sabina,Sales,117500.0,1410000.0
39,112,EMP0112,Sabina,HR,135000.0,1620000.0
40,122,EMP0122,Aarya,Marketing,42500.0,510000.0
41,126,EMP0126,Sita,Marketing,180000.0,2160000.0
42,131,EMP0131,Rita,HR,170000.0,2040000.0
43,138,EMP0138,Pooja,IT,235000.0,2820000.0
44,140,EMP0140,Rahul,Finance,55000.0,660000.0
45,141,EMP0141,Sneha,Marketing,37500.0,450000.0
46,143,EMP0143,Ramesh,IT,220000.0,2640000.0
47,144,EMP0144,Sanjay,Finance,67500.0,810000.0
48,145,EMP0145,Anita,HR,70000.0,840000.0
49,146,EMP0146,Anita,Operations,210000.0,2520000.0
50,148,EMP0148,Aarav,Sales,45000.0,540000.0
51,149,EMP0149,Sabina,Analytics,150000.0,1800000.0
52,150,EMP0150,Kiran,Finance,37500.0,450000.0

## 6. Close the connection

In [76]:
cur.close()
conn.close()
print("Connection closed.")

Connection closed.